(function(){var D={Version:"7.6.7367.23301"};if("undefined"!==typeof window){var c=window.sfx;var t=window.cfx}else c=require("./jchartfx.system.js"),t=c.cfx,module.exports=D;t.highlow=D;var B=function(u,a){this.a=this.b=0;u.x==a.x?(this.a=u.x,this.b=c.D.e):(this.a=(a.y-u.y)/(a.x-u.x),this.b=a.y-this.a*a.x)};B.prototype={d:function(u){if(c.D.h(this.b)){var a=this.a;u=u.a*a+u.b}else a=(u.b-this.b)/(this.a-u.a),u=this.a*a+this.b;return new c.e(a,u)}};var y=function(c){this.b=null;this.k=this.l=!1;this.c=
this.a=this.d=this.e=null;this.m=c};y.prototype={h:function(u){u?(this.e=new c.aB,this.d=new c.aB):this.d=this.e=null},g:function(){null!=this.b&&(this.b=null);null!=this.a&&(this.a=null)},j:function(c,a){this.l&&c.J(a,this.m,null,this.e)},f:function(c,a,b){this.k&&(a.c.sidk(this.c),c.l(a,b,this.b,this.a,null,this.d))}};var E=function a(){a._ic();this.E=this.F=0;this.u=this.D=this.o=this.p=null;this.t=0;this.r=!1;this.j=null;this.e=0;this.n=null;this.q=0;this.x=this.a=null;this.k=!1;this.m=this.b=
null;this.h=this.K=this.g=!1;this.H=0;this.w=this.c=null;this._0_1()};D.HighLow=E;E.prototype={_0_1:function(){this.z=this.A=this.L=this.M=this.C=c._CE;this.A=c.m.k(255,0,0);this.z=c.m.k(128,0,0);this.y="LessThan";this.C=c.m.k(128,128,128);this.B="EqualsTo";this.f=new y(1);this.d=new y(-1);this.i=new y(0);return this},getBaseline:function(){return this.E},setBaseline:function(a){this.E=a;this.g=!0},getBaselineMax:function(){return this.F},setBaselineMax:function(a){this.F=a;this.K=!0},getEqualsToLine:function(){return this.C},
setEqualsToLine:function(a){this.C=a=c.m._t(a)},getEqualsToTag:function(){return this.B},setEqualsToTag:function(a){this.B=a},getLessThanColor:function(){return this.A},setLessThanColor:function(a){this.A=a=c.m._t(a)},getLessThanLine:function(){return this.z},setLessThanLine:function(a){this.z=a=c.m._t(a)},getLessThanTag:function(){return this.y},setLessThanTag:function(a){this.y=a},getSingleArea:function(){return this.k},setSingleArea:function(a){this.k=a},getTemplate:function(){return null==this.b?
null:this.b.t},setTemplate:function(a){null==a?this.b=null:(null==this.b&&(this.b=(new t._Zt)._0_Zt()),this.b.sv(a))},P:function(a,b,d,m,h,k,p,l){var f=new c.e(0,0),e=this.a.Se();k&&(0>h&&0<this.e&&(this.c.A[e-1]=l),this.c.A[e-2]=this.c.A[e-1]);if(!a){var n=this.a.A[e-2].x,g=this.a.A[e-1].x,x=this.a.A[e-1].y,r=new B(new c.e(n,this.a.A[e-2].y),new c.e(g,x)),q=new B(new c.e(n,this.c.A[e-2]),new c.e(g,this.c.A[e-1]));1E-5<c.a.d(r.a-q.a)?f._cf(r.d(q)):f._i1(g,x);this.j.Si(new c.f(f.x,f.y));this.p.Si(h);
f.x!=g&&f.x!=n||this.H++;e--}if(0!=this.e||1!=e){g=2*e;a||g++;n=c.f._ca(g);for(g=q=0;g<e;g++,q++)n[q]._cf(this.a.A[g]);a||(n[q]=c.e.f(f),q++);for(g=e-1;0<=g;g--,q++)n[q]._i1(this.a.A[g].x,this.c.A[g]);x=b.x;r=0<this.e?this.f:0>this.e?this.d:this.i;this.k?(r.l=!0,r.e.A(n),a&&(this.f.j(this,b),this.d.j(this,b))):0!=this.e&&this.J(b,this.e,n,null);if(null!=this.m||null!=this.o||this.g){g=e;a||g++;n=c.f._ca(g);var z=this.f.b,A=this.f.a,v=this.f.c;var w=0<=this.e?this.m:this.o;this.g&&(null==w&&(w=this.n),
0>=this.e&&(z=r.b,A=r.a,v=r.c));if(null!=w){for(g=q=0;g<e;g++,q++)n[q]._cf(this.a.A[g]);a||(n[q]=c.e.f(f));this.k?(r.d.H(),r.d.w(n),r.k=!0):(b.c.sidk(v),this.l(b,w,z,A,n,null))}w=this.g?null:0>this.e?this.m:this.o;if(null!=w){for(g=q=0;g<e;g++,q++)n[q]._i1(this.a.A[g].x,this.c.A[g]);a||(n[q++]=c.e.f(f));b.c.sidk(this.d.c);this.l(b,w,this.d.b,this.d.a,n,null)}this.k&&a&&(this.f.f(this,b,null!=this.m?this.m:this.n),this.d.f(this,b,null!=this.o?this.o:this.n),this.i.f(this,b,this.n))}b.i&=-16385;b.x=
x;if(b.b.a.a){x=b.d;r=b.e;q=b.bj;null==this.u&&(this.u=(new t.cM)._01cM(c.m.c(),1,0),this.D=(new t.cM)._01cM(c.m.c(),1,2));if(0<this.e){n=this.u;var C=this.D;w=5;var y=-5}else n=this.D,C=this.u,w=-5,y=5;n.sm(this.M);C.sm(this.L);z=e;A=0;0!=this.q&&(A=1,z--);0==h&&z++;b.d=0;g=b.bj=0;for(v=A;g<z;g++,v++)b.e=this.q+g,b.aZ(new c.e(this.a.A[v].x,this.a.A[v].y+y),C,0);C=b.aQ;g=c.TD(this.d.b,c.as);null!=g&&(b.aQ=g.j());b.d=1;b.bj=1;g=0;for(v=A;g<z;g++,v++)b.e=this.q+g,b.aZ(new c.e(this.a.A[v].x,this.c.A[v]+
w),n,0);b.aQ=C;b.d=x;b.e=r;b.bj=q}a||(k&&0!=h&&0!=this.e&&h!=this.e&&(e++,d=0<this.e?p:l,this.c.A[e-2]=d,this.c.A[e-1]=d,n=this.a.A[e-2].x,g=this.a.A[e-1].x,x=this.a.A[e-1].y,r=new B(new c.e(n,this.a.A[e-2].y),new c.e(g,x)),q=new B(new c.e(n,this.c.A[e-2]),new c.e(g,this.c.A[e-1])),e=c.f._ca(2),e[0]=c.e.f(f),1E-5<c.a.d(r.a-q.a)?f._cf(r.d(q)):f._i1(g,x),e[1]=c.e.f(f),this.l(b,null,null,this.i.a,e,null)),this.a.clear(),this.c.clear(),this.a.Si(f),this.c.Si(f.y),this.a.Si(m),this.c.Si(d))}},T:function(a){this.f.h(this.k);
this.d.h(this.k);this.i.h(this.k);this.a=new c._L;this.c=new c._L;this.x=new c._L;this.w=new c._L;this.j=new c._L;this.p=new c._L;this.H=0;this.L=a.b.a.b;this.g?(this.d.b=new c.as(this.A),this.d.a=(new c.ap)._03ap(this.z,a.b.j.a),this.i.b=null,this.i.a=(new c.ap)._03ap(this.C,a.b.j.a)):(this.d.b=a.x.b(),this.d.a=(new c.ap)._03ap(a.v.d(),a.b.j.a),a.aJ(a.d-1),a.V(!0));this.f.b=a.x;this.f.a=(new c.ap)._03ap(a.v.d(),a.b.j.a);this.M=a.b.a.b;this.h=!1;if(null!=this.b&&null!=this.b.k){var b=this.b.k.a("useFill");
null!=c.TD(b,c.b)&&(this.h=!0)}this.g?(b=a.d,this.f.c=this.v(a,b,this.h,b),this.d.c=this.G(b,this.h,!1),this.i.c=this.G(b,this.h,!0)):(b=a.d-1,this.f.c=this.v(a,b,this.h,b),this.d.c=this.v(a,b+1,this.h,b+1))},G:function(a,b,c){var d="Attribute";b||(d+="Line");d+=" ";d=c?d+this.B:d+this.y;b||(d+="Line");b=(new t.c8)._01c8(d);b.c="C,"+a.toString();return b},v:function(a,b,c,m){b=new t.ca(b,-1);b.d=!c;c||(b.e|=1);b.f=m;b.e|=4;return a.b8(b)},ic5:function(a,b,c,m){switch(b){case 5:return"%s\n%l - %l\n%v - %v\n%s2\n%v~ - %v~";
case 11:return this.Q(c);case 13:this.g?c.b=1:c.a=",0,1"}return null},ic6:function(a){return this.g?1:2},ic7:function(a){return 1602564},ic8:function(a,b,d){a.b=1;a.a=0;var m=a=!1;if(d.e==d.o){m=!0;null==this.getTemplate()&&this.R();null!=this.b&&null!=this.b.k&&(b=this.b.k.a("upTemplate"),this.m=c.TD(b,t._Zt),b=this.b.k.a("downTemplate"),this.o=c.TD(b,t._Zt),b=this.b.k.a("lineTemplate"),this.n=c.TD(b,t._Zt));if(this.r)return;this.q=d.e;this.T(d)}else if(d.e==d.q){if(!this.g&&(this.r=!this.r,!this.r)){this.O();
return}a=!0}else if(this.r)return;var h=d.w,k=0,p=!1;if(this.g){var l=this.E;this.K&&this.E!=this.F&&(k=this.F,p=!0)}else 0<d.n?l=d.a.d.iaW().getItem(d.d+1,d.e):(l=h,h=d.a.d.iaW().getItem(d.d-1,d.e));if(!d.T&&1E108!=l){b=p?h>k?1:h<l?-1:0:h==l?0:h<l?-1:1;var f=d.p.a;this.g||0<d.n?l=d.j.valueToPixel(l):(l=f,f=d.j.valueToPixel(h));k=h=p?d.j.valueToPixel(k):l;var e=l;if(0>b||0>this.e)k=l;f=new c.e(d.p.b,f);this.x.Si(f);this.w.Si(k);if(m)this.e=this.t=b,this.a.Si(f),this.c.Si(k);else{if(b==this.e&&(0!=
b||this.g?(this.a.Si(f),this.c.Si(k)):(this.a.A[0]=new c.f(f.x,f.y),this.c.A[0]=k),!a))return;0==this.t&&(this.t=b);this.a.Si(f);this.c.Si(k);if(0!=this.e||this.g||a)if(this.P(b==this.e,d,k,f,b,p,e,h),0!=b||p||(this.a.clear(),this.c.clear(),this.a.Si(f),this.c.Si(k)),a&&b!=this.e&&(this.e=b,this.P(!0,d,k,f,b,p,e,h)),a){m=this.x.I();d.c.sidk(this.f.c);h=f=p=null;null!=this.b&&null!=this.b.k&&(p=this.n,f=this.b.k.a("upFullTemplate"),f=c.TD(f,t._Zt),l=this.b.k.a("downFullTemplate"),h=c.TD(l,t._Zt));
d.i|=16384;if(null!=f||null!=h){l=c.f._ca(m.length+this.j.Se()-this.H);k=b;for(e=this.j.Se()-1;0<=e;e--)0==this.p.A[e]?this.p.A[e]=k:k=this.p.A[e];null!=f&&(this.N(l,this.t,1,b),this.l(d,f,null,null,l,null));null!=h&&(this.N(l,-this.t,-1,b),this.l(d,h,null,null,l,null))}if(!this.g){d.aJ(0);d.V(!1);d.c.sidk(this.f.c);this.l(d,p,this.f.b,this.f.a,m,null);for(e=0;e<m.length;e++)m[e].y=this.w.A[e];d.aJ(1);d.V(!1);d.c.sidk(this.d.c);this.l(d,p,this.d.b,this.d.a,m,null)}d.i&=-16385;null!=p&&p._dispose1(!1);
null!=f&&f._dispose1(!1);null!=h&&h._dispose1(!1);null!=this.b&&this.b._dispose1(!1)}this.e=b;this.q=d.e;a&&this.g&&this.O()}}},l:function(a,b,d,m,h,k){if(null!=b){var p=a.v;a.v=m;a.x=d;d=c.d.b;this.h||(a.i|=131072);m=b.id().L.A;for(var l=m.length,f=0;f<l;f++){var e=m[f],n=e.c;"Points"==n||"P"==n?e.sa(h):"Data"==n?e.sa(k):b.m(e,a,this,d)}b.r(a.c,d,1,0);a.v=p;this.h||(a.i&=-131073)}else a.c.idD(m,h)},O:function(){this.f.g();this.d.g();this.i.g();this.u=this.D=null},N:function(a,b,d,m){m=0;var h=c.C.b;
m<this.j.Se()&&(h=this.j.A[0].x);for(var k=0,p=-1,l=0;l<a.length;l++,k++){var f=this.x.A[k],e=this.w.A[k];f.x>h&&(b=this.j.A[m],b.x!=f.x&&b.x!=p&&(a[l]._cf(b),l++),b=this.p.A[m]*d,m++,h=m<this.j.Se()?this.j.A[m].x:c.C.b);0>b?a[l]._i1(f.x,e):a[l]._i1(f.x,f.y);p=f.x}},R:function(){if(void 0!=t._Zt){var a="HighLow";this.g&&(a+="Baseline");a=t.eU.i(a,!0);null==a&&(a='<DataTemplate xmlns:x="a" xmlns:sys="b"><DataTemplate.Resources><DataTemplate x:Key="lineTemplate"><Canvas><Polyline Points="{Binding Path=Points}" Stroke="{Binding Path=Stroke}" StrokeThickness="{Binding Path=StrokeThickness}"/></Canvas></DataTemplate><LinearGradientBrush x:Key="opacityMask" StartPoint="0,0" EndPoint="0,1"><GradientStop Offset="0" Color="#FFFFFFFF" /><GradientStop Offset="1" Color="#00FFFFFF" /></LinearGradientBrush></DataTemplate.Resources><Polygon Points="{Binding Path=PointsPolygon}" Fill="{Binding Path=Fill}" OpacityMask="{StaticResource opacityMask}"/></DataTemplate>');
null!=a&&this.setTemplate(a)}},J:function(a,b,d,m){if(0<b){var h=this.f.b;var k=a.d-1}else h=this.d.b,k=a.d;var p=a.d;this.g?k=0<b?this.v(a,p,!0,p):0>b?this.G(k,!0,!1):this.G(k,!0,!0):(p--,k=this.v(a,k,!0,p));a.c.sidk(k);a.x=h;k=c.d.b;a.i|=16384;if(null!=this.b){h=this.b.id().L.A;p=h.length;for(var l=0;l<p;l++){var f=h[l],e=f.c;"PointsPolygon"==e||"P"==e?f.sa(d):"CurrentSeries"==e?f.sa(0<b?0:1):"Data"==e?f.sa(m):this.b.m(f,a,this,k)}this.b.r(a.c,k,1,0)}else a.c.idT(h,d)},Q:function(a){a=a.a;a.b=1;
a.c=4096;return null}};E._dt("highlow.HighLow",c.SA,0,t.ic4)})();
