(function(){if("undefined"!==typeof window){var m=window.sfx;var e=window.cfx}else m=require("./jchartfx.system.js"),e=m.cfx;e.radarVersion="7.6.7367.23301";var D=function a(){a._ic();this.d=this.e=null;this.k()};e.by=D;D.prototype={getCircular:function(){return 0!=(this.a&4)},setCircular:function(a){this.b(4,a)},getClockwise:function(){return 0!=(this.a&32)},setClockwise:function(a){this.b(32,a)},getClosed:function(){return 0!=(this.a&8)},setClosed:function(a){this.b(8,a)},getFillArea:function(){return 0!=
(this.a&2)},setFillArea:function(a){this.b(2,a)},getShadows:function(){return 0!=(this.a&16)},setShadows:function(a){this.b(16,a)},getShowLines:function(){return 0!=(this.a&1)},setShowLines:function(a){this.b(1,a)},ic5:function(a,b,c,e){switch(b){case 11:return this.j(c);case 18:return 3}return null},ic6:function(a){return 1},ic7:function(a){return 8397382},ic8:function(a,b,c){a.a=1;a.b=0;a=c.a.d.c;var k=c.l._nc();if(c.h.getVisible()){b=new m.g(0,0);var l=c.h.getLabelsCore();if(0!=l.Se()){var p=new m._p1(void 0);
l=l.iee(p,c.c,c.h.getFont(),!1);b._cf(l)}else l=m.b.k(c.bp,"{0}",a),b._cf(c.c.idZ(l,c.h.getFont()).e());k.m(-b.w,-b.h)}b=new m._pN(q,h,f,g);e.bQ.E(b,k,!0,!0);var q=b.a;var h=b.b;var f=b.c;var g=b.d;f=m.a.o(f,1);g=m.a.o(g,1);l=0!=(c.i&2);p=360/a;var d=c.h.az()?l?45:p:c.h.getStep();this.getClockwise()||(p=-p,d=-d);k=this.o(c,q,h,f,g,k,d);if(D.m(c,q,h,f,g,d,k,this.getCircular())){g=l?0:-90;d=k=0;for(var n=c.u;n<=c.r;n++)if(c.d=n,c.aJ(n),!c.g(8192)){var x=!1,r=0,A=0,G=0,B=0,u=0,C=0,y=0,E=c.M,J=c.I,F=
f/(J-E);this.d=null;for(var t=0;t<a;t++){c.e=t;c.ag();c.V(!0);var v=c.w;l&&(g=this.getClockwise()?c.a$:-c.a$);b.a=g;e.bT.a(b);g=b.a;e.df.i(v)?0==t?x=!0:e.df.i(y)||(b.Y(k,d),this.c(b,c,G,B,r,A,n,t,t-1,!0,q,h),k=b.a,d=b.b):(v<=J&&v>=E&&((v-=E,r=v*F,e.bT.c(b,g,r,r,q,h),r=b.a,A=b.b,0==t||e.df.i(y))?0==t&&(u=r,C=A):(b.Y(k,d),this.c(b,c,G,B,r,A,n,t,t-1,!1,q,h),k=b.a,d=b.b)),G=r,B=A);y=v;g+=p;c.af(0,0)}e.df.i(y)||(c.ad=!1,c.ag(),c.V(!0),this.getClosed()||(u=r,C=A),b.Y(k,d),this.c(b,c,r,A,u,C,n,c.e,c.e,x,
q,h),k=b.a,d=b.b,c.af(0,0),x||0==(this.a&8)||(c.e=0,c.ad=!1,c.ag(),c.V(!0),b.Y(k,d),this.c(b,c,u,C,u,C,n,0,0,!0,q,h),k=b.a,d=b.b,c.af(0,0)))}c.al-=a-1;c.e=c.q}},ieU:function(a,b){0!=(b.ieZ()&2)?(a=this.a,a=e.bQ.c(b,"ShowLines",a,1,!0,!0),a=e.bQ.c(b,"FillArea",a,2,!1,!0),a=e.bQ.c(b,"Circular",a,4,!1,!0),a=e.bQ.c(b,"Closed",a,8,!0,!0),a=e.bQ.c(b,"Clockwise",a,32,!0,!0),this.a=a=e.bQ.c(b,"Shadows",a,16,!1,!0)):this.a=b.ifb(null,this.a,41)},ifg:function(a){this.e=a},o:function(a,b,c,k,l,p,q){var h=a.c,
f=a.h,g=m.e._ca(3);g[0].x=b;g[0].y=c;var d=this.getCircular(),n=this.getShadows(),x=a.bJ(),r=m.a.d(360/q);if(n&&0!=x.a){var A=~~(x.r/(r+1));var G=~~(x.g/(r+1));var B=~~(x.b/(r+1))}else n=!1,A=G=B=0;var u=f.c.a,C=null,y=0!=(a.t&8),E=null,J=null,F=null;y&&(C=(new e.c8)._01c8("PlotArea"),E=f.a6(u),J=(new e.c8)._01c8(e.dd.ab(f,"Line",-1,!0)),F=(new e.c8)._01c8(e.dd.ab(a.j,"Line",-1,!0)));var t=new m.as(x),v=a.h.U.c(m.m.b),V=a.j.U.c(m.m.b);d&&(n||h.idO(t,p.x,p.y,2*k,2*l));var H=u.w,N=null;H&&(N=a.bt(u,
4));u=f.getLabelsCore();var Q=u.Se(),M=f.getFont(),R=f.getTextColor(),w=0!=(a.i&2)?0:270,z=x;h.sidk(null);var I=new m._p2(O,P);e.bT.c(I,w,k,l,b,c);var O=I.a;var P=I.b;for(var K=0;K<r;K++){var L=f.getVisible();L&&(y&&h.sidk(f),D.n(a,r,u,Q,M,R,O,P,w,K));w+=q;I.a=w;e.bT.a(I);w=I.a;e.bT.c(I,w,k,l,b,c);var S=I.a;var T=I.b;g[1].x=O;g[1].y=P;g[2].x=S;g[2].y=T;this.getClockwise()&&e.bQ.B(g[1],g[2]);n&&(t=new m.as(z));y&&h.sidk(C);d?n&&h.idR(t,p,w-q,q):(h.idS(t,g),y&&h.sidk(J),h.idw(v,O,P,S,T));if((0==K||
H)&&L){if(0==K){var U=F;L=V;if(4==a.ao||0==a.ao)H?(U=E,L=N):L=null}else U=E,L=N;null!=L&&(h.sidk(U),h.idw(L,b,c,O,P),0!=K&&y&&h.sidk(E))}O=S;P=T;n&&(z=K>=~~((r+1)/2)?K==r?x:m.m.l(x.a,z.r+A,z.g+G,z.b+B):m.m.l(x.a,z.r-A,z.g-G,z.b-B))}d&&(y&&h.sidk(J),h.idq(v,p.x,p.y,2*k,2*l));return r},c:function(a,b,c,k,l,p,q,h,f,g,d,n){g||(b.aY(q,f,!0),this.getFillArea()&&(a=m.e._ca(3),a[0].x=c,a[0].y=k,a[1].x=l,a[1].y=p,a[2].x=d,a[2].y=n,d=null,0!=(b.t&8)&&(d=b.c.idk(),null==this.d&&(n=new e.bS(b.ca,b.d,b.e,!0,!1,
0),n.i=!0,this.d=n),b.c.sidk(this.d)),b.c.idS(b.x,a),0!=(b.t&8)&&b.c.sidk(d)),this.getShowLines()&&b.c.idw(b.v,c,k,l,p));l=h;0>b.b.p?(p=-b.b.p,l+=p-1):p=m.a.o(b.b.p,1);0!=b.b.c&&0==l%p&&(b.aA(q,f),b.a4(c,k,0));b.c.sidk(null);b.b.a.a&&-1!=f&&(q=0,f!=h&&(q|=2),b.aZ(new m.e(c,k),null,q));return!0},l:function(){null!=this.e&&this.e.iai(16777248)},k:function(){this.a=41},b:function(a,b){this.a=b?this.a|a:this.a&~a;this.l()},j:function(a){a=a.a;a.b=8;0==a.c&&(a.c=4096);return null}};D.n=function(a,b,c,
k,l,p,q,h,f,g){var d=0;270==f||90==f?d=1:90<=f&&270>=f&&(d=2);f=180<=f?2:0;b=0!=k?c.ief(g):0!=(a.i&2)?a.h.r.c(360*g/b)+"\u00b0":a.h.r.c(a.h.az()?g+1:g*a.h.a2());b=a.bb(a.h,b);(new e.cM)._01cM(p,d,f).l(a.c,l,b,new m.e(q,h))};D.m=function(a,b,c,k,l,p,q,h){var f=a.M,g=a.I;if(f>=g)return!1;var d=a.j,n=d.o;if(0==(n&64)&&(d.az()&&d.calculateStep(a.a,a.c,l,!0),l=d.a2(),n=0==(n&1),0<l)){var x=d.r,r=d.getFont(),A=d.getLabelsCore(),G=A.Se(),B=d.getTextColor(),u=d.c.a,C=u.w,y=a.bt(u,4);B=(new e.cM)._01cM(B,
0,0);var E=k/(g-f),J=a.c.idZ(x.c(a.I),r).e().h,F=0!=(a.t&8),t=null;F&&(t=d.a6(u));u=0!=u.v;for(var v=0,D=0,H=f+l;H<=g;H+=l){var N=270,Q;var M=Q=(H-f)*E;if(5>m.a.d(Q-k))break;C&&h&&(F&&a.c.sidk(t),a.c.idq(y,b-M,c-M,2*M,2*M));for(var R=0;R<=q;R++){var w=new m._p2(z,w);e.bT.c(w,N,Q,M,b,c);var z=w.a;w=w.b;if(0!=R)if(C&&!h)F&&a.c.sidk(t),a.c.idw(y,v,D,z,w);else break;else n&&(0!=G?(v=e.bT.g((H-f)/d.ad+.1),v=A.ief(v)):v=x.c(H),v=a.bb(d,v),F&&a.c.sidk(d),B.l(a.c,r,v,new m.e(z+4,w-~~(J/2)))),u&&(F&&a.c.sidk(t),
a.c.idw(y,z-2,w,z+2,w));N+=p;v=z;D=w}}}return!0};D._dt("GR",m.SA,0,e.ic4,e.ieT,e.iff)})();
