(function(){var x={Version:"7.6.7367.23301"};if("undefined"!==typeof window){var k=window.sfx;var m=window.cfx}else k=require("./jchartfx.system.js"),m=k.cfx,module.exports=x;m.funnel=x;var z=function(m,a){this.b=this.c=0;m.x==a.x?(this.b=m.x,this.c=k.D.e):(this.b=(a.y-m.y)/(a.x-m.x),this.c=a.y-this.b*a.x)};z.prototype={a:function(m){return 0==this.b?0:k.D.h(this.c)?this.b:(m-this.c)/this.b}};var v=function a(){a._ic();this.r=null;this.j=!1;this.a=null;this.h=0;this.x=this.e=this.f=null;this.b=this.t=
this.c=this.u=this.d=0;this._0_1()};x.Funnel=v;v.prototype={_0_1:function(){this.n=-1;this.q=5;this.i=30;this.m=10;this.o=this.g=!1;this.p=(new m.Line)._01_2(9);this.E();return this},getConic:function(){return this.j},setConic:function(a){this.j=a;this.k()},getFaces:function(){return 0==this.h?4:this.h},setFaces:function(a){this.h=k.a.o(a,3);this.k()},getLabelInside:function(){return this.g},setLabelInside:function(a){this.g=a;this.k()},getLabelLine:function(){return this.p},getLabelLineAsSeries:function(){return this.o},
setLabelLineAsSeries:function(a){this.o=a;this.k()},getSeparation:function(){return-1!=this.n?this.n:this.q},setSeparation:function(a){this.n=a;this.k()},getTemplate:function(){return null==this.a?"":this.a.t},setTemplate:function(a){this.x=a;null==a?this.a=null:(null==this.a&&(this.a=(new m._Zt)._0_Zt()),this.a.sv(a));this.C()},getTipHeight:function(){return this.i},setTipHeight:function(a){this.i=a},getTipWidth:function(){return this.m},setTipWidth:function(a){this.m=a},ic5:function(a,c,b,e){switch(c){case 11:return this.z(b);
case 12:return!0;case 18:return 1}return null},ic6:function(a){return 1},ic7:function(a){return 142622977},ic8:function(a,c,b){a.a=1;a.b=0;if(a=b.g(256))b.bn=!0;c=b.a.d.iaQ();var e=b.l._nc();e.w-=b.a.q;e.y+=b.a.q;e.h-=b.a.q;if(b.b.a.a&&!this.g){for(var g=0,f=0;f<c;f++){b.K=b.Z.getItem(b.d,f);var d=b.b9();d=b.c.idZ(d,b.J).w;g=k.a.o(g,d)}g+=8;2!=b.b.a.f&&(e.x+=g);e.w-=g}g=e.h;d=e.w;var p=this.getSeparation(),t=983040|b.b.m;a||(t|=134217728);0!=p&&(t|=3145728);var h=-g;var n=e.c();f=e.y;var l=new m.a_,
q=new m.a_;l.b=e.x;l.a=f+-1*p;l.c=0;q.b=e.g();q.a=n- -1*p;q.c=b.a.e;var v=~~((e.g()+e.x)/2);90<b.f.ib$()?(b.y=-1,b.o=c-1,b.e=b.o,b.q=0):(b.y=1,b.o=0,b.e=0,b.q=c-1);var u=0,r=b.R,y=b.ae;if(y){for(f=r=0;f<c;f++){b.aK(b.d,f,!1);var w=b.Z.getItem(b.d,f)*b.a3;r+=w}if(0==r)return}b.b0=r;this.F(b,e);for(f=b.bG=0;f<c;f++){b.ag();if(y){if(0==b.a3){b.af(0,1);continue}b.K*=b.a3;u+=b.K}else u=b.U;b.a_=u;if(0!=b.K&&1E108!=b.K){0>b.y?(w=g-u/r*g,q.a=l.a- -1*p,l.a=n+-1*w):(w=u/r*g,l.a=q.a+-1*p,q.a=n+-1*w);w=e.y-
q.a;var B=0;b.g(33554432)&&(B|=1);b.aK(b.d,b.e,!1);b.V(!0);b.aA(b.d,b.e);var x=t;f==c-1&&(x|=3145728);this.A(b.c,l._nc(),q,B,h,w,b,a,x);w=b.K/r;b.b.a.a&&this.B(b,d,g,l,q,v,n,w,e);b.bG=u}b.af(0,1)}b.al-=c-1;b.e=b.q;null!=this.a&&this.a._dispose1(!1)},ieU:function(a,c){a=new k._p1(this.h);c.ie9(a,"Faces",0);this.h=a.a;a.a=this.n;c.ie9(a,"Separation",-1);this.n=a.a;a.a=this.i;c.ie_(a,"TipHeight",30);this.i=a.a;a.a=this.m;c.ie_(a,"TipWidth",10);this.m=a.a;a.a=this.x;c.ie3(a,"Template");this.x=a.a;a.a=
this.j;c.ifa(a,"Conic",!1);this.j=a.a;a.a=this.g;c.ifa(a,"LabelInside",!1);this.g=a.a;a.a=this.o;c.ifa(a,"LabelLineAsSeries",!1);this.o=a.a},ifg:function(a){this.r=a;this.p.ifg(this.r)},F:function(a,c){var b=~~((c.x+c.g())/2),e=this.m*c.w/100;this.d=b-e/2;this.c=b+e/2;this.u=(c.h-this.getSeparation()*(a.a.d.iaQ()-1))*this.i/100;this.b=c.c()-this.u;this.t=a.b0*this.i/100;a=c.y;this.f=new z(new k.e(c.x,a),new k.e(this.d,this.b));this.e=new z(new k.e(c.g(),a),new k.e(this.c,this.b))},E:function(){if(void 0!=
m._Zt){var a=m.eU.i("Funnel",!0);null!=a&&this.setTemplate(a)}},D:function(a,c,b){var e=!1,g=b[0].y,f=b[2].y,d=b;if(c.bG<this.t||0==c.b0){if(g<this.b&&b[2].x==b[3].x)return d=k.e._ca(6),d[0]._i1(this.e.a(g),g),d[1]._i1(this.f.a(g),g),d[2]._i1(this.f.a(this.b),this.b),d[3]._i1(d[2].x,f),d[5]._i1(this.e.a(this.b),this.b),d[4]._i1(d[5].x,f),a.a=1,d;b[0]._i1(this.d,g);b[1]._i1(this.c,g);e=!0}c.a_<this.t?(b[2]._i1(this.c,f),b[3]._i1(this.d,f),a.a=2):e&&this.b<f?(d=k.e._ca(6),d[0]._i1(this.e.a(g),g),d[1]._i1(this.f.a(g),
g),d[2]._i1(this.d,this.b),d[3]._i1(this.d,f),d[4]._i1(this.c,f),d[5]._i1(this.c,this.b),a.a=1):(b[0]._i1(this.e.a(g),g),b[1]._i1(this.f.a(g),g),b[2]._i1(this.f.a(f),f),b[3]._i1(this.e.a(f),f));return d},C:function(){this.q=5;if(null!=this.a){var a=this.a.k;null!=a&&(a=a.a("cfxDefSeparation"),a=k.TD(a,k.b),null!=a&&(this.q=k.u.e(a)))}},B:function(a,c,b,e,g,f,d,p,t){if(!a.ae){var h=new m.a_,n=a.b.a;p=n.f;n=n.c;a.g(256)&&(p=0);switch(n){case 0:h.a=g.a;break;case 2:h.a=e.a;break;default:h.a=~~((e.a+
g.a)/2)}e=a.b9();this.g?1!=p?(c=v.l(h.a-d,~~(c/2),b),h.b=0==p?f-c:f+c,h.b=2==p?h.b-~~(a.aU/2):h.b+~~(a.aU/2)):h.b=f:(2==p?(h.b=t.g(),c=-2,f=h.a>this.b?this.c:this.e.a(h.a),f+=4,p=0):(h.b=t.x,c=2,f=h.a>this.b?this.d:this.f.a(h.a),f-=4,p=2),0!=this.p.d?(b=k.m.b,this.o&&(b=a.v.d()),b=this.p.c(b),a.c.idw(b,f,h.a,h.b+c,h.a)):h.b=f,n=1);h.c=~~(a.a.e/2);h=a.f.icq(h,0);e=a.bb(a.j,e);a.bQ(e,h,p,n,this.g,0)}},A:function(a,c,b,e,g,f,d,p,t){(new m.a_)._cf(c);var h=m.a_._ca(4);var n=m.a_._ca(4);m.a_._ca(4);var l=
~~((c.b+b.b)/2);var q=~~((c.c+b.c)/2);var A=b.a-c.a;var u=b.b-c.b;var r=b.c-c.c;u=~~(u/2);var y=~~(r/2);if(0!=g){r=v.l(f,u,g);var w=v.l(f,y,g);var x=new k._p1(void 0);v.w(x,4,l,b.a,q,u-r,y-w,h,-1);r=v.l(f+A,u,g);w=v.l(f+A,y,g);v.w(x,4,l,c.a,q,u-r,y-w,n,-1)}l=null;0!=g&&(l=k.e._ca(4),l[0].x=h[1].b,l[0].y=b.a,l[1].x=h[3].b,l[1].y=b.a,l[2].y=c.a,l[2].x=n[3].b,l[3].x=n[1].b,l[3].y=c.a);if(b.a!=c.a)if(r=new k._p1(0),l=this.D(r,d,l),h=r.a,r=k.d.b,n=null,p)this.j||0!=(d.aG&4)||(h=0),1==h&&(c.a=l[2].y),2!=
h&&(this.j?d.f.icd(d.c,c,b,d.x,d.v,null,t,e,g,f,this.h):d.f.ics(d.c,c,b,d.x,d.v,null,t,e,g,f,this.h)),0!=h&&(a=(b.b-c.b)/2*(g+this.u)/g,r=c.b+a,c=b.b-a,b=k.a.d(c-r)/2,a=(new m.a_)._01a_(r,l[2==h?0:2].y,q-b),c=(new m.a_)._01a_(c,l[2==h?3:4].y,q+b),this.j?d.f.icf(d.c,a,c,d.x,d.v,null,t,e):d.f.ice(d.c,a,c,d.x,d.v,null,t,e,this.h));else if(null!=this.a){e=this.a.id().L.A;t=e.length;for(q=0;q<t;q++)switch(a=e[q],a.c){case "P":case "PointsPolygon":a.sa(l);break;case "X":a.sa(k.a.p(c.b,b.b));break;case "W":a.sa(k.a.d(b.b-
c.b));break;case "Y":a.sa(k.a.p(c.a,b.a));break;case "H":a.sa(k.a.d(b.a-c.a));break;case "G":case "Geometry":null==n&&(n=new k.aB,n.z(l));a.sa(n);break;default:this.a.m(a,d,this,r)}this.a.r(d.c,k.d.b,1,0)}else a.idS(d.x,l),a.idz(d.v,l)},k:function(){null!=this.r&&this.r.iai(16777248)},z:function(a){a=a.a;0==a.c&&(a.c=1);0==a.d&&(a.d=1);return null}};v.l=function(a,c,b){return~~(a*c/b)};v.w=function(a,c,b,e,g,f,d,m,t){var h;c=k.a.o(k.a.d(c),2);c=k.a.p(c,4);var n=6.28318530717959/c;var l=k.a.u(n);var q=
k.a.i(n);var p=1;for(t=h=0;t<c;t++){m[t].a=e;m[t].b=b+k.a.k(f*h+.5);m[t].c=g+k.a.k(d*p+.5);var u=p*q+h*l;h=h*q-p*l;p=u}a.a=n;return c};v._dt("funnel.Funnel",k.SA,0,m.ic4,m.ieT,m.iff);void 0!==m.UserInterface&&m.UserInterface.prototype.galleryMap["1"].push("=funnel.Funnel,Funnel")})();
