(function(){var m={Version:"7.6.7367.23301"};if("undefined"!==typeof window){var e=window.sfx;var d=window.cfx}else e=require("./jchartfx.system.js"),d=e.cfx,module.exports=m;d.heatmap=m;var p=function v(){v._ic();this.b=this.c=0;this._0_1()};m.ColorGradientStop=p;p.prototype={_0_1:function(){this.a=this.d=e._CE;return this},getColor:function(){return this.d},setColor:function(d){this.a=this.d=d=e.m._t(d)},getOffset:function(){return this.c},setOffset:function(e){this.c=e},ieU:function(d,t){d=new e._p1(this.d);
t.ie4(d,"Color");this.d=d.a;d.a=this.c;t.ie_(d,"Offset",0);this.c=d.a}};p._dt("heatmap.ColorGradientStop",e.SA,0,d.ieT);var r=function t(){t._ic()};m.ColorGradientCollection=r;r.prototype={_0_1:function(){this.a=new e._L;return this},getCount:function(){return this.a.Se()},getItem:function(e){return this.a.A[e]},setItem:function(e,a){this.a.A[e]=a},add:function(e){this.a.Si(e)},clear:function(){this.a.clear()},e:function(d){var a=this.a.Se(),c=this.a.A[0];if(d==c.b)return c.a;for(var b=1;b<a;b++){var l=
this.a.A[b],f=l.b;if(f==d)return l.a;if(f>d)return b=f-c.b,a=(d-c.b)/b,d=(f-d)/b,c=c.a,l=l.a,e.m.k(c.r*d+l.r*a,c.g*d+l.g*a,c.b*d+l.b*a);c=l}return c.a},insert:function(e,a){this.a.Sl(e,a)}};r._dt("heatmap.ColorGradientCollection",e.SA,0,e.Sa);var u=function a(){a._ic();this.d=this.b=null;this.i=this.j=this.c=this.f=this.e=0;this.n=null;this._0_1()};m.HeatMap=u;u.prototype={_0_1:function(){this.a=(new r)._0_1();this.g=4;var a=new p;a.setColor(e.m.k(192,0,0));this.a.add(a);a=new p;a.setColor(e.m.k(0,
192,0));this.a.add(a);this.h=60;this.q();void 0!==d.motif?d._Em("heatmap",this,arguments):1<=arguments.length&&this.setStyle(arguments[0]);return this},iej:function(){return!1},iek:function(){return null},iel:function(){return!0},getGradientStops:function(){return this.a},getLegendHeight:function(){return this.g},setLegendHeight:function(a){this.g=a},getTemplate:function(){return null==this.d?null:this.d.t},setTemplate:function(a){this.n=a;null==this.d&&(this.d=(new d._Zt)._0_Zt());this.d.sv(a)},
icz:function(a){this.b=e.TD(a,d.Chart);null==this.b||this.b.iP()||this.b.getLegendBox().getItemAttributes().getItemList(this.b.getSeries()).setVisible(!1);return!0},ic5:function(a,c,b,e){switch(c){case 11:return this.p(b);case 13:b.b=1}return null},ic6:function(a){return 1},ic7:function(a){return 33837056},ic8:function(a,c,b){c=b.c;a.b=1;a.a=0;a=0!=(b.t&8);if(b.e==b.o&&b.d==b.u){0==this.j&&this.l();for(var l=!0,f=this.a.getCount(),g=c.idk(),h=0;h<f;h++){var k=this.a.getItem(h),n=k.d;if(a){var q=(new d.c8)._01c8("HeatMap"+
h.toString());c.sidk(q);n=c.idl()._Gv("fill",n,null,0)}k.a=n;k.b=k.c;0!=k.b&&(l=!1)}a&&c.sidk(g);if(l&&1<f)for(g=l=1/(f-1),h=1;h<f;h++)k=this.a.getItem(h),k.b=g,g+=l}if(!(b.T||b.w<this.c||(h=b.j,l=b.h,f=e.a.k(h.valueToPixel(b.d)),h=e.a.k(h.valueToPixel(b.d+1)),k=e.a.k(l.valueToPixel(b.e+.5)),l=e.a.k(l.valueToPixel(b.e+1.5)),h<f))){a&&(a=(new d.c8)._01c8(null),g=c.idj().ieJ(b.c.idk()),a.c=g.ift(1),a.e=g.ift(0),c.sidk(a));a=this.a.e((b.w-this.c)/this.j);a=new e.as(a);f=(new e.d)._02c(k,f,l-k,h-f);if(null!=
this.d){b.x=a;a=this.d.id().L.A;h=a.length;for(k=0;k<h;k++)this.d.m(a[k],b,this,f);this.d.r(c,f,1,0)}else c.idV(a,f);b.b.a.a&&(b.D=0,b.an=0,b.p.b=f.x+f.w/2,b.p.a=f.y,b.aa=f.y+f.h,b.O=1,b.ah=1,b.b.a.c=1,b.b.a.n=1)}},ic$:function(a,c,b,e){},ida:function(a){null!=this.b&&this.l();return!1},idb:function(a,c,b,e){return!1},iem:function(a){},ien:function(a,c,b,e){this.e=0},ieo:function(){return this.m()?1:this.g},iep:function(a){return!1},ieq:function(a,c,b,d,f){a.a=!0;f._cf(e.g.b);a=c.idZ(this.k(this.f),
b).e();this.m()&&(c=c.idZ(this.k(this.c),b).e(),this.i=e.a.o(a.w,c.w),a.w=2*this.i+this.h,a.w=.8*d.w,this.h=a.w-2*this.i);return a},ier:function(a,c,b){a.a=null;b=0==this.e?this.f:this.c;a.b=0==this.e||this.e==this.g-1?this.k(b):" ";a.c=null;a.d=this.e;var d=this.m(),f=this.g;d&&(f=1);if(this.e>=f)return!1;b=c.c;c.b.c=0;if(0==this.e){var g=c.F,h=c.F+f*c.aU-c.A,k=c.aq;b.sidk(null);f=new e.c;var n=new e.e(0,0),q=new e.e(0,0);d?(k+=this.i,q._i1(k,g),n._i1(k+this.h,g),f._i2(k,g,this.h,h-g+2)):(k-=6,n._i1(k,
g),q._i1(k,h),f._i2(k,g+1,13,h-g-2));g=(new e.aD)._0aD(n,q,this.a.getItem(1).a,this.a.getItem(0).a);h=this.a.getCount();if(2<h){k=new e.ay(h);n=e.m._ca(h);q=Array(h);for(var m=0;m<h;m++){var p=this.a.getItem(h-1-m),r=m;n[r]=p.a;q[r]=1-p.b}k.sb(n);k.sc(q);g.sk(k)}c.c.idU(g,f);g=this.b.iL(13);0!=(b.idh()&8)&&(g=b.idl()._Gv("fill",g,"LegendItem",0));g=(new e.ap)._01ap(g);b.idE(g,f);d&&(d=new e.au,d.sd(1),g=c.b.a.h,c=new e.as(c.b.a.b),h=~~((f.y+f.c())/2),b.idI(a.b,g,c,new e.e(f.g()+4,h),d),k=this.k(this.c),
d.sb(2),b.idI(k,g,c,new e.e(f.x-4,h),d),a.b="")}this.e++;return!0},ieU:function(a,c){a=new e._p1(this.g);c.ie9(a,"LegendHeight",3);this.g=a.a;a.a=this.n;c.ie3(a,"Template");this.n=a.a;this.a=c.ifc("GradientStops",this.a,"ColorGradientCollection",4)},k:function(a){return this.b.getAxisY().getDataFormat().c(a)},q:function(){if(void 0!=d._Zt){var a=d.eU.i("HeatMap",!0);null!=a&&this.setTemplate(a)}},m:function(){var a=this.b.getLegendBox().ibR();return 3==a||1==a},l:function(){var a=this.b.getAxisY(),
c=a.getLabels();c.clear();c.add("");for(var b=this.b.getSeries().c.A,d=b.length,f=0;f<d;f++){var g=b[f].getText();null==g&&(g="");c.add(g)}a.setMin(c.Se()-1);a.setMax(0);a.setLabelValue(1);a.setStyle(a.o|512);this.c=e.D.c;this.f=e.D.d;a=this.b.k;c=a.b;b=a.c;for(d=0;d<c;d++)for(f=0;f<b;f++)g=a.getItem(d,f),1E108!=g&&(this.c=e.a.p(this.c,g),this.f=e.a.o(this.f,g));this.j=this.f-this.c},p:function(a){a=a.a;a.b=8;0==this.j&&this.l();a.e=this.c;a.f=this.f;0==a.c&&(a.c=35);return null}};u._dt("heatmap.HeatMap",
e.SA,0,d.icy,d.ic4,d.ic9,d.iei,d.iq,d.ieT)})();
