(function(){var w={Version:"7.6.7367.23301"};if("undefined"!==typeof window){var b=window.sfx;var p=window.cfx}else b=require("./jchartfx.system.js"),p=b.cfx,module.exports=w;p.xyz=w;w.XYZStyles={AverageNormals:1};var E=function P(){P._ic()};w.XYZPointYIndexComparer=E;E.prototype={_0_1:function(){return this},SH:function(b,r){return b.c==r.c?0:b.c<r.c?-1:1}};E._dt("xyz.XYZPointYIndexComparer",b.SA,0,b.SG);var H=function(b,r){this.c=b;this.b=r;this.a=0};H.prototype={_i1:function(b,r){this.c=b;this.b=
r;this.a=0}};H._ca=function(b){for(var r=Array(b),d=0;d<b;d++)r[d]=new H;return r};var L=function(b,r){this.a=new p.a_;this.f=r.b-b.b;this.e=r.a-b.a;this.d=r.c-b.c;this.a._cf(b)};L.prototype={b:function(b,r){var d=(b-this.a.a)/this.e;r.b=this.a.b+this.f*d;r.c=this.a.c+this.d*d;r.a=b}};var I=function r(){r._ic()};w.XYZColorComparer=I;I.prototype={_0_1:function(){return this},SH:function(b,d){return b.a==d.a?0:b.a<d.a?-1:1}};I._dt("xyz.XYZColorComparer",b.SA,0,b.SG);var M=function d(){d._ic();this.j=
this.h=null;this.f=this.n=0;this.m=this.i=!1;this.a=this.l=0;this.g=null;this.d=0;this.k=!1;this.e=0;this._0_1()};w.XYZColor=M;M.prototype={_0_1:function(){this.c=this.b=b._CE;return this},getColorFrom:function(){return this.b},setColorFrom:function(d){this.b=d=b.m._t(d)},getColorTo:function(){return this.c},setColorTo:function(d){this.c=d=b.m._t(d)},getFrom:function(){return this.f},setFrom:function(d){this.f=d},getTo:function(){return this.e},setTo:function(d){this.e=d},o:function(d){d=d>this.a?
(d-this.a)/this.l:0;this.i&&(d=1-d);var l=1-d;return b.m.k(this.b.r*l+this.c.r*d,this.b.g*l+this.c.g*d,this.b.b*l+this.c.b*d)},p:function(d,l){this.k=b.m.o(this.c,this.b);this.n=b.a.d(this.e-this.f);var k=this.f,a=this.e;this.a=l.valueToPixel(k);this.d=l.valueToPixel(a);var c=this.b,g=this.c;if(this.d<this.a){c=this.c;g=this.b;k=this.e;a=this.f;var h=this.a;this.a=this.d;this.d=h;this.i=!0}else this.i=!1;this.l=this.d-this.a;if(this.k||0==d)this.h=Array(1),this.h[0]=new b.as(this.b),this.g=Array(1),
this.g[0]=this.d;else{d=b.a.h(this.n/d);this.h=Array(d);this.j=b.m._ca(d);this.g=Array(d);var e=d-1;h=c.r;var f=c.g,t=c.b,u=k,z=(g.r-c.r)/e,p=(g.g-c.g)/e;c=(g.b-c.b)/e;k=(a-k)/e;for(a=0;a<d;a++)this.j[a]=b.m.k(h,f,t),this.h[a]=new b.as(this.j[a]),this.g[a]=l.valueToPixel(u),h+=z,f+=p,t+=c,u+=k}}};M._dt("xyz.XYZColor",b.SA,0);var O=function(d,b,k){this.c=d;this.b=b;this.a=k},D=function(){this.a=this.b=0};w.Point2D=D;D.prototype={_i1:function(d,b){this.b=d;this.a=b},_01_2:function(d,b){this._i1(d,b);
return this}};var y=function(){};y.c=function(d,l,k,a){if(b.a.d(l.a-k.a)<b.D.b&&b.a.d(k.a-a.a)<b.D.b)return!1;if(b.a.d(k.a-l.a)<b.D.b){var c=-(a.b-k.b)/(a.a-k.a);var g=.5*(k.b+a.b);a=.5*(k.a+a.a);l=.5*(k.b+l.b);var h=c*(l-g)+a}else{if(b.a.d(a.a-k.a)<b.D.b){h=-(k.b-l.b)/(k.a-l.a);var e=.5*(l.b+k.b);var f=.5*(l.a+k.a);l=.5*(a.b+k.b)}else h=-(k.b-l.b)/(k.a-l.a),c=-(a.b-k.b)/(a.a-k.a),e=.5*(l.b+k.b),g=.5*(k.b+a.b),f=.5*(l.a+k.a),a=.5*(k.a+a.a),l=(h*e-c*g+a-f)/(h-c);h=h*(l-e)+f}c=k.b-l;k=k.a-h;e=c*c+k*
k;c=d.b-l;k=d.a-h;return c*c+k*k<=e};y.b=function(d){var l=new b._L,k=d.Se();if(3>k)return l;for(var a=4*k,c=d.A[0].b,g=d.A[0].a,h=c,e=g,f=1;f<k;f++)d.A[f].b<c&&(c=d.A[f].b),d.A[f].b>h&&(h=d.A[f].b),d.A[f].a<g&&(g=d.A[f].a),d.A[f].a>e&&(e=d.A[f].a);f=h-c;var t=e-g;f=f>t?f:t;c=.5*(h+c);g=.5*(e+g);d.Si((new D)._01_2(c-2*f,g-f));d.Si((new D)._01_2(c,g+2*f));d.Si((new D)._01_2(c+2*f,g-f));l.Si(new O(k,k+1,k+2));for(f=0;f<k;f++){g=new b._L;for(e=0;e<l.Se();e++)y.c(d.A[f],d.A[l.A[e].c],d.A[l.A[e].b],d.A[l.A[e].a])&&
(g.Si(new B(l.A[e].c,l.A[e].b)),g.Si(new B(l.A[e].b,l.A[e].a)),g.Si(new B(l.A[e].a,l.A[e].c)),l.Sn(e),e--);if(!(f>=k)){for(e=g.Se()-2;0<=e;e--)for(c=g.Se()-1;c>=e+1;c--)g.A[e].Sw(g.A[c])&&(g.Sn(c),g.Sn(e),c--);for(e=0;e<g.Se();e++){if(l.Se()>=a)throw(new b.P)._0P("Exceeded maximum edges");l.Si(new O(g.A[e].b,g.A[e].a,f))}g.clear()}}for(f=l.Se()-1;0<=f;f--)(l.A[f].c>=k||l.A[f].b>=k||l.A[f].a>=k)&&l.Sn(f);d.Sn(d.Se()-1);d.Sn(d.Se()-1);d.Sn(d.Se()-1);return l};y.a=function(d,l,k){var a=new b._L;for(d=
d.Sb();1==d.SK();){var c=d.SM(),g=(new D)._01_2(c.b,c.c);a.Sj(g)||(a.Si(g),l.Si(c))}l=y.b(a).A;a=l.length;for(d=0;d<a;d++)c=l[d],k.Si(c.c),k.Si(c.b),k.Si(c.a)};var B=function a(b,k){a._ic();this.b=b;this.a=k};B.prototype={Sw:function(b){return this.b==b.a&&this.a==b.b||this.b==b.b&&this.a==b.a}};B._dt("CWGE",b.SA,0,b.IEquatable_1);var N=function k(){k._ic()};w.XYZColorCollection=N;N.prototype={_0_1:function(){this.a=new b._L;return this},getCount:function(){return this.a.Se()},getItem:function(b){return this.a.A[b]},
setItem:function(b,a){this.a.A[b]=a},add:function(b){this.a.Si(b)},clear:function(){this.a.clear()},insert:function(b,a){this.a.Sl(b,a)}};N._dt("xyz.XYZColorCollection",b.SA,0,b.Sa);var F=function a(){a._ic();this.a=this.i=null;this.g=this.k=0;this._0XYZ()};w.XYZ=F;F.prototype={_0XYZ:function(){this.h=new b._L;this.b=(new N)._0_1();this.l=20;this.c=1;return this},getAxisZ:function(){return this.i},setAxisZ:function(a){this.i=a},getColors:function(){return this.b},getStyle:function(){return this.c},
setStyle:function(a){this.c=a},e:function(a,c,g,b,e,f,t,u){var h=e.Se(),p=t[0],A=t[1],q=t[2];0>p&&(e.Si(a._nc()),p=h++,t[0]=p);0>A&&(e.Si(c._nc()),A=h++,t[1]=A);0>q&&(e.Si(g._nc()),q=h++,t[2]=q);0!=u&&this.o(a,c,g)!=u&&(a=A,A=q,q=a);-1==b?(f.Si(p),f.Si(A),f.Si(q)):(f.A[b]=p,f.A[b+1]=A,f.A[b+2]=q)},o:function(a,c,b){var g=(new p.a_)._01a_(~~((a.b+c.b+b.b)/3),~~((a.a+c.a+b.a)/3),~~((a.c+c.c+b.c)/3));a=this.j(a,g);var e=this.n(a,g);c=this.j(c,g);b=this.j(b,g);var f=this.d(c,e);e=this.d(b,e);return 0>=
e&&0<f?-1:0>=f&&0<e?1:0==f&&0==e?0<this.d(c,a)&&0>this.d(b,a)?1:-1:0<this.d(this.n(c,b),g)?1:-1},icz:function(a){return!0},ic5:function(a,c,b,h){switch(c){case 26:return 410;case 25:return"MC"}return null},ic6:function(a){return 2},ic7:function(a){return 20992},ic8:function(a,c,g){a.b=1;a.a=0;if(g.e==g.o){this.h.clear();this.k=this.i.u;this.g=this.i.x-this.k;0==this.g&&(this.g=1);c=g.j;a=c.aQ;var h=c.aR,e=this.b.getCount();if(0==e){var f=new M;f.m=!0;this.b.add(f);e=1}1==e&&(f=this.b.getItem(0),f.f=
a,f.e=h,f.m&&(f.b=g.b.h,f.c=g.b.q));this.a=Array(e);h=(h-a)/this.l;for(a=0;a<e;a++){var t=this.b.getItem(a);this.a[a]=t;t.p(h,c)}1<e&&(a=(new I)._0_1(),b.F.f(this.a,a))}a=g.p.b;h=(g.Z.getItem(g.d+g.n,g.e)-this.k)/this.g*g.a.e;0<g.n?(c=g.p.a,e=h):(e=g.p.a,c=h);this.h.Si((new p.a_)._01a_(a,c,e));if(g.e==g.q){g.al-=b.a.d(g.q-g.o)+1;c=new b._L;e=new b._L;y.a(this.h,c,e);f=e.Se();var u=p.a_._ca(3),z=H._ca(3),w=Array(3);for(a=0;3>a;a++)z[a]._i1(0,a);var A=(new E)._0_1();h=new b.as(b.m.k(255,0,0));t=(new b.ap)._01ap(b.m.k(0,
0,0));if(0!=(g.f.ica()&4)){var q=new b._L;if(1>=this.b.getCount())for(f=this.b.getItem(0),a=0;a<c.Se();a++)q.Si(f.o(c.A[a].a));else{for(a=0;a<f;a+=3){for(var n=0;3>n;n++)w[n]=e.A[a+n],z[n].c=c.A[w[n]].a,z[n].b=n;b.F.f(z,A);for(n=0;3>n;n++)u[n]._cf(c.A[w[z[n].b]]),z[n].a=this.m(u[n].a);0<b.a.d(z[0].a-z[2].a)&&this.p(u,z,a,c,e)}for(a=0;a<c.Se();a++)u=c.A[a].a,f=this.m(u),f=this.a[f],q.Si(f.o(u))}g.f.icp(g.c,c.I(),c.Se(),h,t,e,q,this.c)}else a=new b._L,a.Si(0),a.Si(1),a.Si(2),g.f.icp(g.c,c.I(),c.Se(),
h,t,e,null,this.c)}},ic$:function(a,c,b,h){},ida:function(a){return!1},idb:function(a,c,b,h){return!1},ieU:function(a,c){},n:function(a,c){return(new p.a_)._01a_(a.a*c.c-a.c*c.a,a.c*c.b-a.b*c.c,a.b*c.a-a.a*c.b)},d:function(a,c){return a.b*c.b+a.a*c.a+a.c*c.c},m:function(a){for(var c=this.a.length,b=0;b<c;b++){var h=this.a[b];if(a<h.a||a>=h.a&&a<h.d)return b}return c-1},p:function(a,c,b,h,e){var f=c[0].a,g=c[1].a,u=c[2].a,w=new L(a[0],a[1]),D=new L(a[0],a[2]),A=new L(a[1],a[2]),q=new p.a_,n=new p.a_,
x=e.A[c[0].b+b],v=e.A[c[1].b+b],y=e.A[c[2].b+b],B=v,m=Array(3),G=0;a=a[1].a;for(var K=this.o(h.A[x],h.A[v],h.A[y]),E=0;f<=u;f++,E++){var J=f<u?this.a[f+1]:this.a[f];var C=G;G=J.a;0!=E&&C<a&&G>a&&(G=a,f--,g--);if(0!=E||g==f)if(f<u){D.b(G,q);A.b(G,n);C=F.xZDistance(h.A[x],q);J=F.xZDistance(h.A[x],n);var H=F.xZDistance(h.A[v],q),I=F.xZDistance(h.A[v],n);C+I>J+H&&(C=x,x=v,v=C);m[0]=x;m[1]=v;m[2]=-1;this.e(h.A[x],h.A[v],q,b,h,e,m,K);b=-1;C=v;m[0]=C;m[1]=m[2];m[2]=-1;this.e(h.A[v],q,n,b,h,e,m,K);x=m[1];
v=m[2]}else J=c[1].a==c[2].a,q._cf(h.A[B]),n._cf(h.A[y]),m[0]=x,m[1]=v,C=J?B:y,m[2]=C,this.e(h.A[x],h.A[v],h.A[C],b,h,e,m,K),b=-1,J&&(m[0]=v,m[1]=B,m[2]=y,this.e(h.A[v],h.A[B],q,b,h,e,m,K));else f<u?(w.b(G,q),D.b(G,n)):(q._cf(h.A[c[1].b+b]),n._cf(h.A[y])),m[0]=x,m[1]=-1,m[2]=-1,this.e(h.A[x],q,n,b,h,e,m,K),b=-1,x=m[1],v=m[2],g++}},j:function(a,b){return(new p.a_)._01a_(a.b-b.b,a.a-b.a,a.c-b.c)}};F.xZDistance=function(a,c){return b.a.v((a.b-c.b)*(a.b-c.b)+(a.c-c.c)*(a.c-c.c))};F._dt("xyz.XYZ",b.SA,
0,p.icy,p.ic4,p.ic9,p.ieT)})();
