(function(){var t={Version:"7.6.7367.23301"};if("undefined"!==typeof window){var a=window.sfx;var b=window.cfx}else a=require("./jchartfx.system.js"),b=a.cfx,module.exports=t;b.data=t;t.CrosstabAggregate={Sum:0,First:1,Last:2,Avg:3,Min:4,Max:5};t.HoltWintersMethod={Additive:0,Multiplicative:1};var N=function ma(){ma._ic();this.a=this.b=this.c=null};t.TransformValues=N;N._dt("CWDIT",a.SA,0);var E=function na(b,c,p,t,I,O){na._ic();this.c=null;this.f=b;this.d=c;this.e=p;this.c=null!=t?new a.ag(t.I()):
null!=I?I:O.a;this.a=-1};E.prototype={ibw:function(){return this.d.Se()},ibx:function(){return this.d.So(this.a)},iby:function(){return null==this.e?1:this.e.iby()},ibz:function(){return this.a},sibz:function(a){this.a=a},ibA:function(a,b,c,p,t){return this.f.ib(a,b,c,p,t)},ibB:function(){return this.c},ibC:function(){this.a++;return this.a<this.d.Se()},ibD:function(a,b){}};E._dt("CWDIT",a.SA,0,b.ibv);var P=function I(a,b,c){I._ic();this._bc._0bq.call(this,c+a.K(),a.L());this.d=b};P.prototype={M:function(a){return a.g(this.d)}};
P._dt("CWDR",b.bq,0);var Q=function I(a,b){I._ic();this._bc._0bq.call(this,"RateOfChange"+a.K(),a.L());this.d=b};Q.prototype={M:function(a){return a.h(this.d)}};Q._dt("CWDR",b.bq,0);var R=function O(a,b){O._ic();this._bc._0bq.call(this,a,b)};R.prototype={M:function(a){return a.c}};R._dt("CWDH",b.bq,0);var p=function I(){I._ic()};t.TransformWrapper=p;p.prototype={_0_1:function(a){this.b=a;return this}};p._dt("CWDIT",a.SA,0);var T=function S(a,b,c,p){S._ic();this._bc._0_1.call(this,c);this.e=b;this.d=
a;this.c=Array(2*p)};T.prototype={h:function(a){if(0>a){a=this.e;var b=this.d}else a*=2,b=this.c[a],a=this.c[a+1];return 1E108==b?1E108:a/b},g:function(a){return 0>a?this.d:this.c[2*a]},f:function(a,b,c){a*=2;this.c[a]=b;this.c[a+1]=c}};T._dt("CWDR",p,0);var U=function oa(a,b){oa._ic();this._bc._0_1.call(this,a);this.c=b};U._dt("CWDO",p,0);var K=function V(b,c,p){V._ic();this.c=this.f=this.e=0;this._bc._0_1.call(this,c);this.i=new a.E;this.g=this.d=b;this.h=Array(3*p)};K.prototype={k:function(a,b){if(0>
b)return a?this.e:this.f;b*=2;a||b++;return this.h[b]}};K._dt("CWDH",p,0);var L=function pa(b,c,p){pa._ic();this._bc._0bq.call(this,b,a.V.A(a.D));this.e=c;this.d=p};L.prototype={M:function(a){return a.g?a.k(this.e,this.d):1E108}};L._dt("CWDH",b.bq,0);var x=function S(){S._ic()};t.TransformDescriptor=x;x.prototype={_0_4:function(a){this._bc._0bq.call(this,a.K(),a.L());this.d=a;return this},_01_4:function(a,b){this._bc._0bq.call(this,a,b);this.d=null;return this},M:function(a){return this.d.M(a.b)}};
x._dt("CWDIT",b.bq,0);var J=function V(){V._ic()};J.prototype={_0dU:function(a,b,c){this._bc._0_4.call(this,a);this.h=c;return this},_01dU:function(a,b,c,p){this._bc._01_4.call(this,a,b);this.h=p;return this},M:function(b){var c=a.TD(b,W);return null!=c?this.h?"Other":c.b:this.h&&null==this.d?(b=a.TD(b,U),null!=b?a.b.k(null,"Point {0}",b.c+1):""):x.prototype.M.call(this,b)}};J._dt("CWDO",x,0);var X=function qa(a){qa._ic();this._bc._0_4.call(this,a)};X.prototype={M:function(a){return a.d?1E108:x.prototype.M.call(this,
a)}};X._dt("CWDH",x,0);var Y=function ra(a){ra._ic();this._bc._0_4.call(this,a)};Y.prototype={M:function(a){return a.d?a.i:x.prototype.M.call(this,a)}};Y._dt("CWDH",x,0);var Z=function sa(a){sa._ic();this._bc._0_4.call(this,a)};Z.prototype={M:function(a){return a.d?a.c:x.prototype.M.call(this,a)}};Z._dt("CWDH",x,0);var aa=function ta(a,b){ta._ic();this._bc._0bq.call(this,a,b)};aa.prototype={ibk:function(){return 1},M:function(a){return a.e}};aa._dt("CWDC",b.bq,0,b.ibj);var ca=function ba(a,b){ba._ic();
this._bc._0bq.call(this,a,b)};ca.prototype={ibk:function(){return 1},M:function(a){return a.f}};ca._dt("CWDC",b.bq,0,b.ibj);var da=function ba(a){ba._ic();this.a=a};da.prototype={SH:function(b,c){return a.b.c(b.c,c.c,!1,this.a)}};da._dt("CWDC",a.SA,0,a.SG);var fa=function ea(a,b,c,w){ea._ic();this.b=null;this.a=Array(b);this.f=a;this.d=c;this.e=w;this.c=a;2!=this.d&&(this.b=Array(b));for(a=0;a<b;a++)this.a[a]=1E108,null!=this.b&&(this.b[a]=0)};fa.prototype={h:function(a){return a<this.a.length?this.a[a]:
1E108},g:function(b,c){if(b>=this.a.length){for(var y=Array(b+1),w=0;w<this.a.length;w++)y[w]=this.a[w];for(w=this.a.length;w<=b;w++)y[w]=1E108;this.a=y;if(null!=this.b){y=Array(b+1);for(w=0;w<this.b.length;w++)y[w]=this.b[w];for(w=this.b.length;w<=b;w++)y[w]=0;this.b=y}}w=0;null!=this.b&&(w=this.b[b],this.b[b]=w+1);switch(this.d){case 1:if(0!=w)return;break;case 0:0!=w&&(c+=this.a[b]);break;case 3:0!=w&&(c=(c+this.a[b]*w)/(w+1));break;case 4:0!=w&&(c=a.a.p(this.a[b],c));break;case 5:0!=w&&(c=a.a.o(this.a[b],
c))}this.a[b]=c}};fa._dt("CWDC",a.SA,0);var la=function(b,c,y,w){this.c=this.d=this.h=this.a=this.b=this.e=null;this.g=b;this.l=c;this.j=y;this.k=w;c=b.indexOf(";");if(null!=b&&a.b.i(b,",")){if(this.c=b.split(","),b=this.c.length,this.a=Array(b),this.e=new a.aT,-1!=c)for(this.d=Array(b),y=0;y<b;y++)w=this.c[y],c=w.indexOf(";"),-1!=c&&(this.d[y]=w.substr(c+1),this.c[y]=w.substr(0,c))}else-1!=c&&(this.h=b.substr(c+1),this.g=b.substr(0,c))};la.prototype={bA:function(){return null!=this.b?this.b.K():
this.j},m:function(){return null!=this.a||null!=this.h?new ca(this.j,a.V.A(a.b)):new aa(this.b.K(),this.b.L())},i:function(b){if(null!=this.a){this.e.sb(0);for(var c=0;c<this.a.length;c++){var y=this.a[c].M(b);null!=this.d&&null!=this.d[c]&&(y=a.TC(y,a.Sy),y=y.Sz(this.d[c],this.k));0!=c&&this.e.e(this.l);this.e.e(y.toString())}y=this.e.toString()}else y=this.b.M(b),null!=this.h&&(y=a.TC(y,a.Sy),y=y.Sz(this.h,this.k));return y},f:function(a,b,c,w){if(null==this.a){if(null==this.b&&(b==this.g||null==
this.g&&18==c&&!w))return this.b=a,!0}else{for(c=0;c<this.c.length;c++)this.c[c]==b&&(this.a[c]=a,w=!0);return w}return!1}};var ha=function ea(a,b,c){ea._ic();this._bc._0bq.call(this,a,b);this.e=c;this.d=a};ha.prototype={ibk:function(){return 2},M:function(a){return a.h(this.e)}};ha._dt("CWDC",b.bq,0,b.ibj);var ia=function w(a){w._ic();this.a=a};ia.prototype={SH:function(b,c){return a.b.c(b.d,c.d,!1,this.a)}};ia._dt("CWDC",a.SA,0,a.SG);var M=function w(){w._ic();this.e=this.a=null;this.c=!1;this.b=
null;this.d=" - "};M.prototype={getHeading:function(){return this.a},setHeading:function(a){this.a=a},getName:function(){return this.e},setName:function(a){this.e=a},getSeparator:function(){return this.d},setSeparator:function(a){this.d=a},getSort:function(){return this.c},setSort:function(a){this.c=a},getSortID:function(){return this.b},setSortID:function(a){this.b=a},f:function(a,b){null==a&&(a=this.a);return new la(a,this.d,this.e,b)}};M._dt("CWDC",a.SA,0);var ua=function(){this.f=this.g=0;this.e=
null;this.j=this.c=this.d=0;this.b=null;this.a=0;this.i=null;this.h=0},W=function ja(a,b){ja._ic();this.a=a;this.b=b};W._dt("CWDO",a.SA,0);var c=function va(){va._ic()};t.TransformBase=c;c.prototype={f:function(a,c,B,g){var d=(new b.cI)._0cI();a=a.a.A;for(var h=a.length,k=0;k<h;k++){var e=a[k],m=new b.FieldMap;2==e.a&&null!=c?(g&&(m.c=e.getDisplayName(),m.b=e.b,m.a=e.a,d.add(m),m=new b.FieldMap),m.c=e.getDisplayName()+" "+B,m.b=c+e.b):(m.c=e.getDisplayName(),m.b=e.b);m.a=e.a;d.add(m)}return d},c:function(b,
c,B,g,d){var h=new N,k=null,e=null,m=null;b=b.a.A;for(var f=b.length,l=0;l<f;l++){var n=b[l];2==n.a?(n=c.N(n.b,!0),null==k?k=n:(null==e&&(e=new a._L),e.Si(n))):d||1!=n.a||(n=c.N(n.b,!0),null==m&&(m=new a._L),m.Si(n))}c=c.A;b=c.length;for(f=0;f<b;f++){l=c[f];if(!g){if(l==k)continue;if(null!=e&&e.Sj(l))continue}!d&&null!=m&&m.Sj(l)||B.Si((new x)._0_4(l))}h.c=e;h.a=k;h.b=m;return h}};c.g=function(a,b,c){a.e('<Grid Margin="3,2,3,1"><Grid.RowDefinitions>');for(var g=0;g<b;g++)a.e('<RowDefinition Height="Auto"/>');
a.e("</Grid.RowDefinitions><Grid.ColumnDefinitions>");for(g=0;g<c;g++)a.e('<ColumnDefinition Width="Auto"/>');a.e("</Grid.ColumnDefinitions>")};c.j=function(a){a.e('<DockPanel Orientation="Vertical" Margin="3,0,3,3"><TextBlock Text="{Binding Path=SeriesT}" Foreground="{Binding Path=ItemFill}"/>')};c.a=function(a,b,c,g,d,h){var k="";0<b&&(k=' Grid.Row="'+b.toString()+'"');a.e("<TextBlock");a.e(k);null!=g&&(a.e(" "),a.e(g));a.e(' Margin="0,0,10,0" Text="');a.e(c);a.e('"/><TextBlock');a.e(k);null!=h&&
(a.e(" "),a.e(h));a.e(' Grid.Column="1" Text="');a.e(d);a.e('" HorizontalAlignment="Right"/>')};c.i=function(a){a.e('<TextBlock Text="{Binding Path=Macro%v out of %t}" Margin="0,0,10,0"/><TextBlock Grid.Column="1" Text="{Binding Path=Macro(%p%%)}" FontWeight="Bold" HorizontalAlignment="Right"/>')};c.h=function(a){a.e("</DockPanel>")};c.e=function(a){a.e("</Grid>")};c.d=function(a){a.e("</DataTemplate>")};c.b=function(a){a.e('<DataTemplate xmlns:x="a"><DataTemplate.Resources><AxisConverter x:Key="axisConverter"/></DataTemplate.Resources>')};
c._dt("CWDIT",a.SA,0);p=function ja(){ja._ic();this._0_2()};t.RateOfChangeTransform=p;p.prototype={_0_2:function(){return this},k:function(a,b,g){g.Si(new Q(a,b));g.Si(new P(a,b,"Last"))},ib:function(b,B,g,d,h){switch(d){case 0:null!=h&&(h.f=!0,b=b.iab(B).aq.K().substr(12),B=new a.aT,c.b(B),c.g(B,3,2),c.a(B,0,b,null,"{Binding Path=Value}",null),c.a(B,1,"Current:",null,"{Binding Path=Data"+b+",Converter={StaticResource axisConverter}}",null),c.a(B,2,"Previous:",null,"{Binding Path=DataLast"+b+",Converter={StaticResource axisConverter}}",
null),c.e(B),c.d(B),h.a=B.toString())}return null},ibK:function(b){var c=b.c,g=new a._L,d=this.c(b.b,b.a,g,!0,!0),h=d.a;d=d.c;this.k(h,-1,g);var k=0,e=null;if(null!=d){k=d.Se();e=Array(k);for(var m=0;m<k;m++)e[m]=1E108,this.k(d.A[m],m,g)}m=1E108;for(var f,l=new a._L;;){f=m;var n=c.ibx(),q=h.M(n);m=q;f=new T(f,m,n,k);l.Si(f);if(null!=d)for(var u=0,r=d.A,z=r.length,D=0;D<z;D++)q=r[D].M(n),f.f(u,e[u],q),e[u]=q,u++;if(!c.ibC())break}c=new E(this,l,c,g,null,b);b.c=c;b.a=c.ibB();b.b=this.f(b.b,"RateOfChange",
"Rate of Change",!1);c.ibC()}};p._dt("CWDR",c,0,b.ibJ);p=function B(){B._ic();this.m=this.n=null;this.p=0;this._0_2()};t.OthersTransform=p;p.prototype={_0_2:function(){this.k=.05;this.o=-1;this.l=5;return this},getMinPercentage:function(){return this.k},setMinPercentage:function(a){this.k=a},r:function(a,g,d){d.Si((new J)._0dU(a,g,!1))},ib:function(a,g,d,h,b){switch(h){case 0:d==this.o&&this.q(a,g,d,b)}return null},ibK:function(c){var g=c.c,d=new a._L,h=this.c(c.b,c.a,d,!1,!1),k=h.a;this.r(k,-1,d);
if(null!=h.b)for(var e=h.b.A,m=e.length,f=0;f<m;f++){var l=e[f],n=(new J)._0dU(l,-1,!0);null==this.n&&(this.n=l);d.Si(n)}else d.Si((new J)._01dU("Label",a.V.A(a.b),-1,!0));n=new a._L;var q=0;for(e=a.D.c;;){m=g.ibx();n.Si(m);var u=k.M(m);1E108!=u&&(q+=u,e=a.a.p(e,u));if(!g.ibC())break}this.p=q;if(e/q>this.k)g=new E(this,n,g,null,null,c);else{e=new a._L;f=null;for(var r=m=0,z=n.A,D=z.length,v=0;v<D;v++)l=z[v],u=k.M(l),u/q<this.k?(null==f&&(f=new a._L),f.Si(l),m+=u):e.Si(new U(l,r)),r++;q=f.Se();if(null==
f||1>=q)g=new E(this,n,g,null,null,c);else{this.o=e.Se();if(q>this.l){r=Array(q);n=f.I();for(u=0;u<q;u++)l=f.A[u],r[u]=k.M(l);a.F._skv(r,n);k=new a._L;for(u=q-1;0<=u;u--)k.Si(n[u]);f=k}k=new W(f,m);e.Si(k);this.m=k;g=new E(this,e,g,d,null,c);c.a=g.ibB();null==h.b&&(h=new b.FieldMap,h.b="Label",h.a=1,c.b.add(h))}}c.c=g;g.ibC()},q:function(b,g,d,h){if(null!=h){d=this.m.a.Se();var k=a.a.p(this.l,d);b=b.iab(g).aq.d;h.f=!0;g=new a.aT;c.b(g);c.j(g);c.g(g,k+2,2);c.i(g);g.e('<Rectangle Grid.Row="1" Fill="#00FFFFFF" Width="10" Height="6"/>');
for(var e="",m=0;m<k;m++){var f=this.m.a.A[m];null!=this.n&&(e=this.n.M(f));var l=b.M(f);if(m==this.l-1){for(e=m+1;e<d;e++)f=this.m.a.A[m],l+=b.M(f);e=a.b.k(null,"{0} other",d-(this.l-1))}f=a.D._l(l/this.p*100,"f2",null)+"%";c.a(g,m+2,e,null,f,null)}c.e(g);c.h(g);c.d(g);h.a=g.toString()}}};p._dt("CWDO",c,0,b.ibJ);p=function g(){g._ic();this.w=0;this.u=!1;this.l=null;this._0_2()};t.HoltWintersTransform=p;p.prototype={_0_2:function(){this.k=4;this.o=1;this.r=this.t=0;this.n=this.p=this.q=a.D.e;this.m=
!0;return this},getAlpha:function(){return a.D.h(this.q)&&null!=this.l?this.l.g:this.q},setAlpha:function(a){this.q=a},getBeta:function(){return a.D.h(this.p)&&null!=this.l?this.l.f:this.p},setBeta:function(a){this.p=a},getCombineProjection:function(){return this.m},setCombineProjection:function(a){this.m=a},getExtraPeriods:function(){return this.o},setExtraPeriods:function(a){this.o=a},getGamma:function(){return a.D.h(this.n)&&null!=this.l?this.l.c:this.n},setGamma:function(a){this.n=a},getSeason:function(){return this.k},
setSeason:function(a){this.k=a},getSeasonMethod:function(){return this.r},setSeasonMethod:function(a){this.r=a},getTrendMethod:function(){return this.t},setTrendMethod:function(a){this.t=a},O:function(a,d){d=new b.FieldMap;d.b="From";d.a=5;a.add(d);d=new b.FieldMap;d.b="To";d.a=2;a.add(d)},N:function(b,d,h){this.m?h.Si(new Z(b)):(h.Si(new X(b)),h.Si(new R("Projection"+b.K(),a.V.A(a.D))));h.Si(new L("From",!0,d));h.Si(new L("To",!1,d))},z:function(b,d,h,k,e){var g=b.length,c=this.o*d,l=Array(g+c-d),
n=this.H(b,d,this.r),q=n.i,u=n.h,r=n.j;l[0]=r;for(var z=1-h,D=1-k,v=1-e,p=0,t=this.t,x=this.r,F=d;F<g;F++,p++){var A=b[F],G=r,C=F%d,H=u;0==t?0==x?(l[p]=G+H+q[C],r=h*(A-q[C])+z*(G+H),u=k*(r-G)+D*H,q[C]=e*(A-r)+v*q[C]):(r=A/q[C]*h+z*(r+u),u=k*(r-G)+D*u,q[C]=A/r*e+v*q[C],l[p]=(r+u)*q[C]):0==x?(l[p]=G*H+q[C],r=h*(A-q[C])+z*G*H,u=r/G*k+D*H,q[C]=e*(A-r)+v*q[C]):(l[p]=G*H*q[C],r=A/q[C]*h+z*G*H,u=r/G*k+D*H,q[C]=A/r*e+v*q[C])}z=g;D=1;for(F=0;F<c;F++,z++,p++)v=z-g+1,0!=F&&0==F%d&&D++,l[p]=0==t?0==x?r+v*u+q[z%
d]:(r+v*u)*q[z%d]:0==x?r*a.a.q(u,D)+q[z%d]:r*a.a.q(u,D)*q[z%d];n.e=this.K(b,d,h,k,e,c,l);n.b=l;n.g=h;n.f=k;n.c=e;n.d=this.F(b,l,d);return n},M:function(a,d,b){for(var h=[-1E3,-6E4,-36E5,1,30,90,365],g=0;g<h.length;g++)if(this.y(d,b,h[g]))return a.a=!0,h[g];a.a=!1;return-1},L:function(a,d){var b=a.length;var g=0==d%2?~~(d/2):~~((d-1)/2);for(var e=Array(b-d+1),c,f=0;f<b-d+1;f++){var l=0;c=f;for(var n=0;n<d;n++,c++)l+=a[c];e[f]=l/d}a=Array(b);for(f=0;f<g;f++)a[f]=0;c=g;if(0==d%2)for(d=e[0],f=1;f<e.length;f++,
c++)b=e[f],a[c]=(b+d)/2,d=b;else for(f=0;f<e.length;f++,c++)a[c]=e[f];for(f=0;f<g;f++,c++)a[c]=0;return a},ib:function(a,d,b,c,e){switch(c){case 0:return this.I(d,b,e);case 1:this.J(a)}return null},ibK:function(b){var d=b.c,h=new a._L,c=this.c(b.b,b.a,h,!1,!0).a;this.N(c,-1,h);for(var e=0,g=null,f=null,l=-1,n=0;n<h.Se();n++){var q=h.A[n];if(q.L()==a.V.A(a.E)){f=q;g=q.d;g._df=1;h.A[n]=new Y(g);l=n;break}}var u=Array(d.ibw());n=new a._L;q=0;for(var r,z=(new a.E)._01E(1997,1,1),p,v=!1;;){p=d.ibx();r=
c.M(p);u[q]=r;var t=new K(!1,p,0);n.Si(t);null!=g&&(r=g.M(p),0!=q&&(0==e?(v=new a._p1(v),e=this.M(v,z,r),v=v.a):v&&!this.y(z,r,e)&&(v=!1)),z=r);q++;if(!d.ibC())break}r=n.A[q-1];r.g=!0;r.e=u[q-1];r.f=r.e;u=a.D.h(this.q)||a.D.h(this.p)||a.D.h(this.n)?this.E(u,this.k,this.q,this.p,this.n):this.z(u,this.k,this.q,this.p,this.n);u.a=q;var x=u.b,J=this.o*this.k,F=u.b.length-this.k*this.o;if(!this.m){for(var A=0;A<this.k;A++)n.A[A].c=1E108;for(A=this.k;A<q;A++)n.A[A].c=x[A-this.k]}for(A=0;A<J;A++)t=new K(!0,
p,0),t.c=x[F],t.e=t.c-u.e[A],t.f=t.c+u.e[A],v&&(r=this.x(z,e),z=t.i=r),n.Si(t),F++;this.l=u;this.w=e;this.u=v;b.b=this.m?this.f(b.b,null,null,!1):this.f(b.b,"Projection","Projection",!0);if(!this.u&&null!=g)for(h.A[l]=f,e=b.b.a.A,g=e.length,f=0;f<g;f++)if(l=e[f],3==l.a){l.a=1;break}d=new E(this,n,d,h,null,b);b.c=d;b.a=d.ibB();this.O(b.b,c);d.ibC()},y:function(b,d,h){b=this.x(b,h);return 1<=h?b.g()==d.g()&&b.e()==d.e()&&b.c()==d.c():a.E.n(b,d)},K:function(b,d,h,c,e,m,f){for(var g=Array(b.length-d),
k=0,q=d;k<g.length;k++,q++)g[k]=b[q]-f[k];b=this.B(g);f=Array(m);for(k=0;k<m;k++)f[k]=1.959964*a.a.v(this.A(d,h,c,e,k+1,b));return f},J:function(c){this.u&&(c.setExtraStyle(c.H|2097152),0>this.w&&c.getAxisX().r.setFormat(8));var d=c.getSeries(),h=d.getItem(0).getColor(),k=1;if(this.m){c=c.getPoints();var e=(new b.PointAttributes)._0_2();e.setColor(a.m.j(255,h));e.getLine().setStyle(1);e.setTag("Projection");e.o=2;for(var g=this.l.a-1,f=g+this.o*this.k;g<f;g++)c.setItem(0,g,e)}else c=d.getItem(k),
c.setColor(a.m.j(255,h)),c.getLine().setStyle(1),k++;d=d.getItem(k);d.setColor(a.m.j(64,h));d.setGallery(3);d.setTag("=Attribute0 ProjectionConfidence");h=a.TC(d.ac,b.ic2);null!=h&&h.sic3('<DataTemplate xmlns:x="a" xmlns:sys="b"><Polygon Points="{Binding Path=PointsPolygon}" Fill="{Binding Path=Fill}" /></DataTemplate>')},x:function(a,b){var d=a;if(0>b)return a.i(-b);1==b?d=a.h(1):30==b?d=a.j(1):90==b?d=a.j(3):365==b&&(d=a.j(12));return d},I:function(b,d,h){null!=h&&(h.f=!0,d>=this.l.a&&(d=new a.aT,
c.b(d),c.g(d,4,2),c.a(d,0,"Forecast:",'Foreground="{Binding Path=ItemFill}"',"{Binding Path=Value}",null),d.e('<TextBlock Text="95% Confidence" Grid.Row="1" Grid.ColumnSpan="2" Margin="0,4,0,4"/>'),c.a(d,2,"From:",null,"{Binding Path=DataFrom,Converter={StaticResource axisConverter}}",null),c.a(d,3,"To:",null,"{Binding Path=DataTo,Converter={StaticResource axisConverter}}",null),c.e(d),c.d(d),h.a=d.toString()));return this.m?1:2<=b?2:null},H:function(b,d,c){c=new ua;var h=b.length;a.a.r(h/d);var e=
this.L(b,d);if(0==d%2){var g=~~(d/2);var f=1*d;var l=g+f}else g=~~((d-1)/2),f=1*d+1,l=h-g;var n=new a._p2(q,n);this.G(n,e,g,f);var q=n.a;n=n.b;var u=Array(h);for(f=0;f<h;f++)u[f]=b[f]-e[f];b=Array(d);for(f=e=0;f<d;f++){var r=0,p=0;for(h=f+g;h<l;h+=d)r+=u[h],p++;b[f]=r/p;e+=b[f]}l=e/d;for(f=0;f<d;f++)b[f]-=l;if(0==d%2)for(f=0,l=g;f<g;f++,l++)d=b[f],b[f]=b[l],b[l]=d;else{f=Array(d);h=0;for(l=g+1;l<d;l++,h++)f[h]=b[l];for(l=0;l<=g;l++,h++)f[h]=b[l];b=f}c.i=b;c.h=q;c.j=n;return c},G:function(a,b,c,k){for(var d=
0,h=0,f=0,g=0,n=0,q=1;n<k;n++,c++,q++){var u=b[c];d+=q;h+=u;f+=q*q;g+=q*u}a.a=(k*g-d*h)/(k*f-d*d);a.b=h/k-a.a*d/k},F:function(a,b,c){return this.C(a,b,c)/(a.length-c)},E:function(b,d,c,k,e){if(a.D.h(c)){var h=.5;var f=.45;c=.1}else h=c,c=f=0;if(a.D.h(k)){var g=.5;var n=.45;k=.1}else g=k,k=n=0;if(a.D.h(e)){var q=.5;var u=.45;e=.1}else q=e,e=u=0;h=this.v(b,d,10,h,f,g,n,q,u);return this.v(b,d,6,h.g,c,h.f,k,h.c,e)},v:function(b,d,c,k,e,m,f,l,n){var h=a.D.c,g=null,r=~~(c/2),p=e/r,t=f/r;r=n/r;var v=k-e,
x=m-f,E=l-n;0!=e&&(1<k+c*p?v=1-c*p:0>v&&(v=0));0!=f&&(1<m+c*t?x=1-c*t:0>x&&(x=0));0!=n&&(1<l+c*r?E=1-c*r:0>E&&(E=0));k=v;for(e=0;e<c;e++,k+=p)for(m=x,f=0;f<c;f++,m+=t)for(l=E,n=0;n<c;n++,l+=r)v=this.z(b,d,k,m,l),v.d<h&&(h=v.d,g=v);return g},D:function(a,b,c,k,e){b=a*(1+k*b);0==k%e&&(b+=c*(1-a));return b},C:function(a,b,c){for(var d=0,h=0;c<a.length;c++,h++){var g=a[c]-b[h];d+=g*g}return d},B:function(a){for(var b=a.length,c=0,k=0;k<b;k++)c+=a[k];var e=c/b;for(k=c=0;k<b;k++){var g=a[k]-e;c+=g*g}return c/
(b-1)},A:function(a,b,c,k,e,m){var d=1;if(1<e)for(var h=1;h<e;h++){var g=this.D(b,c,k,h,a);d+=g*g}return m*d}};p._dt("CWDH",c,0,b.ibJ);p=function d(){d._ic();this.x=this.t=this.u=this.m=null;this.z=0;this.p=null;this.y=0;this.q=null;this._0_2()};t.CrosstabDataProvider=p;p.prototype={_0_2:function(){this.n=a.aJ.b();this.r=-1;this.o=new a._L;this.k=new M;this.l=new M;this.k.e="Row";this.v=3;return this},getAggregate:function(){return this.v},setAggregate:function(a){this.v=a},ibw:function(){return this.o.Se()},
ibx:function(){return this.o.A[this.r]},iby:function(){return 13},ibz:function(){return this.r},sibz:function(a){this.r=a},ibF:function(){return!0},getColumns:function(){return this.l},getDataSource:function(){this.A(this.u,null);return this.u},setDataSource:function(a){this.u=a;this.A(this.u,null)},getRows:function(){return this.k},getValueName:function(){return this.q},setValueName:function(a){this.q=a},ib:function(a,b,c,e,m){return null},ibA:function(a,b,c,e,m){return null},ibB:function(){this.w(!0);
return this.p},ibC:function(){this.w(!0);this.r++;return this.r<this.o.Se()},ibD:function(a,b){},ibI:function(a){if(null!=a){var b="",c="";a=a.a.A;for(var d=a.length,m=0;m<d;m++){var f=a[m];null==this.k.a&&7==f.a?(0!=b.length&&(b+=","),b+=f.b):null==this.l.a&&6==f.a?(0!=c.length&&(c+=","),c+=f.b):null==this.q&&2==f.a&&(this.q=f.b)}null==this.k.a&&0!=b.length&&(this.k.a=b);null==this.l.a&&0!=c.length&&(this.l.a=c)}return null},ibK:function(a){this.m=a.c;this.w(!1);var c=new E(this,this.o,null,null,
this.p,a);c.ibC();var d=(new b.cI)._0cI(),e=new b.FieldMap;e.b=this.p.So(0).K();e.a=1;d.add(e);for(var m=1;m<this.p.Se();m++)e=new b.FieldMap,e.b=this.p.So(m).K(),e.a=2,d.add(e);a.c=c;a.a=this.p;a.b=d},A:function(a,c){null!=a&&null==this.m&&(this.m=b.DataSourceSettings.r(a,c,null))},B:function(b,c){switch(b){case 3:return c?1:0;case 16:return c.o();case 14:return c;case 18:return a.D.j(c,this.n);default:return 0}},w:function(b){if(null!=this.m&&null==this.t&&(this.t=new a._D,this.x=new a._D,!b||this.m.ibC())){var c=
null,d=this.k.f(null,this.n),e=this.l.f(null,this.n),m=null,f=null;null!=this.k.b&&(m=this.k.f(this.k.b,this.n));null!=this.l.b&&(f=this.l.f(this.l.b,this.n));var l=this.m.ibB();b=new a.X;var n=14,q=null;this.k.c&&(q=new a.X);l=l.A;for(var u=l.length,r=0;r<u;r++){var p=l[r],t=p.K(),v=p.L();v=a.V.g(v);var x=!1;e.f(p,t,v,x)&&(x=!0);d.f(p,t,v,x)&&(x=!0);null!=m&&m.f(p,t,v,x);null!=f&&f.f(p,t,v,x);x||null!=c||t!=this.q&&(null!=this.q||14!=v)||(c=p,n=v)}l=null;for(r=u=0;p=this.m.ibx(),v=e.i(p),t=new a._p1(l),
x=this.t.tryGetValue(t,v),l=t.a,x||(l=new ha(v.toString(),a.V.A(a.D),u),null!=f&&(l.d=f.i(p).toString()),this.t.y(v,l),b.Si(l),u++,r++),v=d.i(p),x=this.x.tryGetValue(t,v),t=t.a,x||(t=new fa(v.toString(),r,this.v,v),null!=m&&(t.c=m.i(p).toString()),this.x.y(v,t),this.k.c?q.Si(t):this.o.Si(t)),p=c.M(p),t.g(l.e,this.B(n,p)),this.m.ibC(););this.l.c&&b.e(new ia(this.n));if(this.k.c)for(q.e(new da(this.n)),c=q.A,e=c.length,m=0;m<e;m++)this.o.Si(c[m]);c=b.Se();e=Array(c+1);e[0]=d.m();for(d=0;d<c;d++)e[d+
1]=b.A[d];this.p=new a.ag(e)}}};p._dt("CWDC",c,0,b.ibE,b.ibv,b.ibJ);t=function h(){h._ic();this.a=this.b=this.c=null};b.bo=t;t._dt("ID",a.SA,0);var ka=function e(b){e._ic();this.c=b;this.a=new a.X};ka.prototype={Se:function(){return this.a.Se()},getItem:function(a){return this.a.A[a]},setItem:function(a,b){this.a.A[a]=b;this.b()},add:function(a){this.a.Si(a);this.b()},clear:function(){this.a.clear();this.b()},b:function(){this.c.e(16384)},indexOf:function(a){return this.a.Sk(a)},insert:function(a,
b){this.a.Sl(a,b);this.b()},remove:function(a){this.a.Sm(a);this.b()},removeAt:function(a){this.a.Sn(a);this.b()}};ka._dt("D",a.SA,0,a.Sc,a.Sa);t=function e(){e._ic()};b.dk=t;t.prototype={ib:function(a,b){return this.c._if(null).getAxisY().ae().c(a)}};t._dt("A",b._Zv,0,b.ia);b.DataSourceSettings.prototype.getTransforms=function(){null==this.e&&(this.e=new ka(this.b));return this.e}})();
