(function(){var F={Version:"7.6.7367.23301"};if("undefined"!==typeof window){var c=window.sfx;var m=window.cfx}else c=require("./jchartfx.system.js"),m=c.cfx,module.exports=F;m.rose=F;var p=function(){};p.h=function(R){return R*c.a.c/180};p.f=function(R){return c.a.k(R+1E-13)};p.e=function(c,a,e){e&&(a.w<a.h?(e=~~((a.h-a.w)/2),a.h=a.w,a.y+=e):(e=~~((a.w-a.h)/2),a.w=a.h,a.x+=e));a.w-=a.w%4;a.h-=a.h%4;c.c=~~(a.w/2);c.d=~~(a.h/2);c.a=~~((a.g()+a.x)/2);c.b=~~((a.y+a.c())/2)};p.d=function(c){for(;360<=
c.a;)c.a-=360;for(;0>c.a;)c.a+=360};p.a=function(m,a,e,b,n,f){var d=new c._p2(g,d);p.b(d,a,e,b,n,f);var g=d.a;d=d.b;m.b=c.a.k(d+.5);m.a=c.a.k(g+.5)};p.b=function(m,a,e,b,n,f){var d=p.h(a);a=c.a.u(d);d=c.a.i(d);0==a&&0==d&&(a=0,d=1);m.b=f+b*a;m.a=n+e*d};p.c=function(c,a){var e=c._nc();c._cf(a);a._cf(e)};var S=function(){this.i=!1;this.c=this.f=0;this.h=!1;this.e=null;this.d=this.b=0;this.g=!1;this.a=new c.e(0,0)};S.prototype={j:function(c){return this.i?this.f*c-this.d:-(this.d+this.f*c)}};var G=function a(){a._ic();
this.l=this.a=this.b=this.j=null;this._0_1()};F.Rose=G;G.prototype={_0_1:function(){this.c=3;this.h=0;this.g=!0;this.f=90;this.x();return this},getCircular:function(){return 0!=(this.c&2)},setCircular:function(a){this.i(2,a)},getClockwise:function(){return 0!=(this.c&1)},setClockwise:function(a){this.i(1,a)},getInternalRadius:function(){return this.h},setInternalRadius:function(a){this.h=a;this.d()},getInvertedLegend:function(){return 0!=(this.c&8)},setInvertedLegend:function(a){this.i(8,a)},getShadows:function(){return 0!=
(this.c&4)},setShadows:function(a){this.i(4,a)},getSideBySide:function(){return this.g},setSideBySide:function(a){this.g=a;this.d()},getStartAngle:function(){return this.f},setStartAngle:function(a){this.f=a;this.d()},getTemplate:function(){return null==this.b?null:this.b.t},setTemplate:function(a){this.l=a;null==this.b&&(this.b=(new m._Zt)._0_Zt());this.b.sv(a);this.d()},n:function(a){return this.a.j(a)},ic5:function(a,c,b,n){switch(c){case 11:return this.q(b);case 12:return 0!=(this.c&8)}return null},
ic6:function(a){return 1},ic7:function(a){a=33579536;this.g&&(a|=128);return a},ic8:function(a,e,b){e=b.a.d.iaQ();this.a=new S;this.a.f=360/e;this.a.i=this.getClockwise();this.a.d=this.f;if(null!=this.b&&null!=this.b.t){this.a.g=!0;for(var n=this.b.id().L.A,f=n.length,d=0;d<f;d++)switch(n[d].c){case "GT":case "GeometryTop":this.a.h=!0}}n=!1;0!=b.b.b&&(n=!0,this.a.e=Array(e));a.a=1;a.b=0;a=b.l._nc();if(b.h.getVisible()){f=new c.g(0,0);d=b.h.getLabelsCore();if(0!=d.Se()){var g=new c._p1(void 0);d=d.iee(g,
b.c,b.h.getFont(),!1);f._cf(d)}else d=c.b.k(b.bp,"{0}",e),f._cf(b.c.idZ(d,b.h.getFont()).e());a.m(-f.w,-f.h)}var l=new c._pN(k,h,u,l);p.e(l,a,!0);var k=l.a;var h=l.b;var u=l.c;l=l.d;u=c.a.o(u,1);l=c.a.o(l,1);this.a.b=c.a.p(u,l);this.a.c=this.h*this.a.b/100;this.a.a._i1(k,h);k=0!=(b.i&2);k=0>=b.h.C?k?45:360/e:b.h.getStep();this.getClockwise()||(k=-k);h=this.w(b,a,k);if(this.t(b,k,h,this.getCircular())){k=!1;l=c.a.p(b.u,b.r);for(h=c.a.o(b.u,b.r);l<=h;l++)if(b.d=l,b.aJ(l),!b.g(8192)){a=b.M;f=b.I;d=(u-
this.a.c)/(f-a);for(g=0;g<e;g++){b.e=g;b.ag();b.aK(b.d,b.e,!1);b.V(!0);b.aY(b.d,b.e,!1);var m=b.K,v=0;k&&(v=this.a.e[g],m+=v);1E108==m?m=0:m<=f&&m>=a&&this.v(b,(v-a)*d,(m-a)*d,k);n&&(this.a.e[g]=m);b.af(0,1)}n&&(k=!0)}b.al-=e-1;b.e=b.q;this.a=null}},ieU:function(a,e){this.c=e.ifb("Flags",this.c,3);a=new c._p1(this.f);e.ie_(a,"StartAngle",90);this.f=a.a;a.a=this.h;e.ie$(a,"InternalRadius",0);this.h=a.a;a.a=this.g;e.ifa(a,"SideBySide",!0);this.g=a.a;a.a=this.l;e.ie3(a,"Template");this.l=a.a},ifg:function(a){this.j=
a},x:function(){if(void 0!=m._Zt){var a=m.eU.i("Rose",!0);null!=a&&this.setTemplate(a)}},w:function(a,e,b){var n=a.c,f=a.h,d=0!=(a.aT&512),g=c.e._ca(3);g[0]._cf(this.a.a);var l=this.getCircular(),k=this.getShadows(),h=a.bJ(),u=c.a.d(360/b);if(k&&0!=h.a&&!d){var K=~~(h.r/(u+1));var v=~~(h.g/(u+1));var w=~~(h.b/(u+1))}else k=!1,K=v=w=0;var x=f.c.a,y=null,B=0!=(a.t&8),C=null,E=null,q=null;B&&(y=(new m.c8)._01c8("PlotArea"),C=f.a6(x),E=(new m.c8)._01c8(m.dd.ab(f,"Line",-1,!0)),q=(new m.c8)._01c8(m.dd.ab(a.j,
"Line",-1,!0)));var H=new c.as(h),z=a.h.U.c(c.m.b),T=a.j.U.c(c.m.b);l&&!k&&(B&&n.sidk(y),n.idO(H,e.x,e.y,2*this.a.b,2*this.a.b));var I=x.w,N=null;I&&(N=a.bt(x,4));x=f.getLabelsCore();var U=x.Se(),M=f.getFont();d=d?c.m.c():f.getTextColor();var A=0!=(a.i&2)?0:270,r=h;n.sidk(null);var t=new c._p2(D,J);p.a(t,A,this.a.b,this.a.b,this.a.a.x,this.a.a.y);var D=t.a;var J=t.b;for(var L=0;L<u;L++){var O=f.getVisible();O&&(B&&n.sidk(f),G.u(a,u,x,U,M,d,D,J,A,L));A+=b;t.a=A;p.d(t);A=t.a;p.a(t,A,this.a.b,this.a.b,
this.a.a.x,this.a.a.y);var P=t.a;var Q=t.b;g[1].x=D;g[1].y=J;g[2].x=P;g[2].y=Q;this.getClockwise()&&p.c(g[1],g[2]);k&&(H=new c.as(r));B&&n.sidk(y);l?k&&n.idR(H,e,A-b,b):(n.idS(H,g),n.sidk(E),n.idw(z,D,J,P,Q));if((0==L||I)&&O){if(0==L){if(J=q,D=T,4==a.ao||0==a.ao)I?(J=C,D=N):D=null}else J=C,D=N;if(null!=D){O=this.a.a.x;var F=this.a.a.y;0!=this.a.c&&(p.b(t,A,this.a.c,this.a.c,this.a.a.x,this.a.a.y),O=t.a,F=t.b);n.sidk(J);n.idw(D,O,F,P,Q);0!=L&&n.sidk(C)}}D=P;J=Q;k&&(r=L>=~~((u+1)/2)?L==u-1?h:c.m.l(h.a,
r.r+K,r.g+v,r.b+w):c.m.l(h.a,r.r-K,r.g-v,r.b-w))}l&&(B&&n.sidk(E),n.idq(z,e.x,e.y,2*this.a.b,2*this.a.b));return u},v:function(a,e,b,n){var f=this.a.c,d=new c.aB;if(0==f){var g=a.b.r/100;var l=(1-g)/2}else g=1,l=0;1!=a.X&&(g/=a.X,l+=a.H*g);var k=this.n(a.e+l),h=this.n(a.e+l+g);g=(k+h)/2;var m=new c.f(0,0),p=new c.f(0,0),v=new c.f(0,0),w=new c.f(0,0),x=2*f,y=this.a.a.x-f,B=this.a.a.y-f;v._cf(this.e(k,0));w._cf(this.e(h,0));this.e(g,0);l=this.e(g,b);var C=v.x-w.x,E=v.y-w.y;m._i1(l.x+C/2,l.y+E/2);p._i1(l.x-
C/2,l.y-E/2);if(0!=e){var q=this.e(g,e);v._i1(q.x+C/2,q.y+E/2);w._i1(q.x-C/2,q.y-E/2)}q=null;this.a.h&&(q=new c.aB);0!=f?(n?(d.r(m,p),d.r(p,w),d.r(w,v)):(d.f((new c.d)._02c(y,B,x,x),h,k-h),d.r(v,m),d.r(m,p)),d.E(),null!=q&&q.r(m,p)):(f=2*b,n?(d.g(this.a.a.x-e,this.a.a.y-e,2*e,2*e,k,h-k),d.g(this.a.a.x-b,this.a.a.y-b,f,f,h,k-h)):(d.u(this.a.a.x,this.a.a.y,w.x,w.y),0<b&&d.g(this.a.a.x-b,this.a.a.y-b,f,f,h,k-h),d.E()),null!=q&&q.g(this.a.a.x-b,this.a.a.y-b,f,f,h,k-h));if(this.a.g){e=c.d.b;n=this.b.id().L.A;
k=n.length;for(f=0;f<k;f++)switch(h=n[f],h.c){case "G":case "Geometry":h.sa(d);break;case "GT":case "GeometryTop":h.sa(q);break;case "SizeItem":h.sa(2*b);break;case "XItem":h.sa(this.a.a.x-b);break;case "YItem":h.sa(this.a.a.y-b);break;default:this.b.m(h,a,this,e)}this.b.r(a.c,e,1,0)}else a.c.idQ(a.x,d),a.c.idy(a.v,d);a.b.a.a&&(b=a.c.idm(),d=new c.aF,d.g(g+90,l),a.c.sidm(d),a.aZ(new c.e(l.x,l.y),null,0),a.c.sidm(b));return!0},t:function(a,e,b,n){var f=a.M,d=a.I;if(f>=d)return!1;var g=a.j,l=g.o;if(0==
(l&64)){0>=g.C&&g.calculateStep(a.a,a.c,this.a.b,!0);var k=c.a.d(g.C);l=0==(l&1);if(0<k){var h=g.r,u=g.getFont(),K=0!=(a.aT&512),v=g.getLabelsCore(),w=v.Se(),x=K?c.m.c():g.getTextColor(),y=g.c.a;K=y.w;var B=a.bt(y,4);x=(new m.cM)._01cM(x,0,0);var C=(this.a.b-this.a.c)/(d-f),E=a.c.idZ(h.c(a.I),u).e().h,q=0!=(a.t&8),H=null;q&&(H=g.a6(y));y=0!=y.v;for(var z=0,F=0,I=f+k;I<=d;I+=k){var N=270,G;var M=G=(I-f)*C+this.a.c;if(5>c.a.d(G-this.a.b))break;K&&n&&(q&&a.c.sidk(H),a.c.idq(B,this.a.a.x-M,this.a.a.y-
M,2*M,2*M));for(var A=0;A<=b;A++){var r=new c._p2(t,r);p.a(r,N,G,M,this.a.a.x,this.a.a.y);var t=r.a;r=r.b;if(0!=A)if(K&&!n)q&&a.c.sidk(H),a.c.idw(B,z,F,t,r);else break;else l&&(0!=w?(z=p.f((I-f)/g.ad+.1),z=v.ief(z)):z=h.c(I),z=a.bb(g,z),q&&a.c.sidk(g),x.l(a.c,u,z,new c.e(t+4,r-~~(E/2)))),y&&(q&&a.c.sidk(H),a.c.idw(B,t-2,r,t+2,r));N+=e;z=t;F=r}}}}return!0},e:function(a,e){var b=new c._p2(void 0,void 0);return this.r(b,a,e)},r:function(a,e,b){e=e*c.a.c/180;a.a=c.a.u(e);a.b=c.a.i(e);b+=this.a.c;return new c.f(this.a.a.x+
b*a.b,this.a.a.y+b*a.a)},d:function(){null!=this.j&&this.j.iN()},i:function(a,c){this.c=c?this.c|a:this.c&~a;this.d()},q:function(a){a.a.b=8;return null}};G.u=function(a,e,b,n,f,d,g,l,k,h){var p=0;270==k||90==k?p=1:90<=k&&270>=k&&(p=2);k=180<=k?2:0;e=0!=n?b.ief(h):0!=(a.i&2)?a.h.r.c(360*h/e)+"\u00b0":a.h.r.c(0>=a.h.C?h+1:h*c.a.d(a.h.C));e=a.bb(a.h,e);(new m.cM)._01cM(d,p,k).l(a.c,f,e,new c.e(g,l))};G._dt("rose.Rose",c.SA,0,m.ic4,m.ieT,m.iff);void 0!==m.UserInterface&&m.UserInterface.prototype.galleryMap["3"].push("=rose.Rose,Rose")})();
